---
title: "Statistics By States"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(readxl)
```

```{r}
abb = read_excel("../data/state_ab.xlsx") %>% mutate(state = str_replace(state, "\\s", ""))

df = read_csv("../data/us_2017.csv") %>% mutate(state = State) %>% filter(state != "District of Columbia") %>% 
  left_join(abb) 

df$state = as.character(df$state)
df$state_ab = as.character(df$state_ab) 
df$number = order(df$state)

clean_df =
  df %>% 
  pivot_longer(
    2:26,
    names_to = "types",
    values_to = "ratio")
  
```

US suicide rate map
=====================================

Column {.sidebar}
-----------------------------------------------------------------------
```{r}

```

Column {.tabset}
-----------------------------------------------------------------------

### US MAP
```{r}

```


### Discription
TODO

Column {data-width=450}
-----------------------------------------------------------------------

### suicide number by year in US

```{r}

```


State statistics by states
=====================================

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
## selection choice set up
variable_types = clean_df %>% distinct(types) %>% pull()

selectInput(
  "select_choice", 
  label = h3("select choice"),
  choices = variable_types, selected = "suicide_rate_per100000")

## top n selection
number = clean_df %>% distinct(number) %>% pull()

selectInput(
  "select_top_n", 
  label = h3("Top n states"),
  choices = number, selected = "50")
```

Column {.tabset}
-----------------------------------------------------------------------

### US map

```{r}
renderPlotly({ 
  geo = list(
        scope = 'usa',
        projection =  list(type = 'albers usa'),
        lakecolor = toRGB('white'))

  df = clean_df %>% 
        filter(
          types == input$select_choice
        ) %>% 
        arrange(ratio) %>%
        top_n(as.numeric(input$select_top_n))
  
  print(df$state)
  df %>%
  plot_geo() %>% 
  add_trace(
    z = ~ratio,
    locations = df$state_ab, locationmode = 'USA-states',
		# add text
		text = ~paste(types, df$state_ab, sep = "")
  ) %>% 
  layout(geo = geo,
         title = "US Map - State Statistics")
})
```


### Discription
Discribe TODO


Column {data-width=450}
-----------------------------------------------------------------------

### Bar plot

```{r}
renderPlotly({ 

  clean_df %>% 
  filter(
    types == input$select_choice) %>% 
    arrange(ratio) %>% 
    top_n(as.numeric(input$select_top_n)) %>% 
      plot_ly(x = ~reorder(state,ratio), y = ~ratio, color = ~state, type = "bar")
})
```

