---
title: "Proposal"
author: "Life savers"
date: "`r Sys.Date()`"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# The group members

Yue Lai  yl4359  
Xue Jin  xj2249 

# The tentative project title

# The motivation for this project
Suicide is a major public health concern globally. According to WHO, about 800,000 people die by suicide in 2016, of which 79% occurred in low- and middle-income countries. Overall, suicide accounts for 1.4% of all deaths worldwide, and has become the second leading cause of death among 15-29 age group. Our group aims to summarize the general trend in global suicide rate over time, and explore possible influential factors related to suicide, including age, gender, country and socioeconomic status. Every suicide is tragic but also preventable. Therefore, we hope to arouse public awareness of suicide prevention and provide illustrative background information for further research and development  of preventive strategies. 

# The intended final products

In the end, we will finish a report, in which we will discuss the trend of suicide over the recent 30 years worldwide and the association between GDP, HDI and suicide rate. Besides, we will create a webpage and a narrated screencast for our project. 

# The anticipated data sources

We utilized a compiled dataset pulled from four other datasets by locations and time. In the dataset, we have HDI (Human development index) from United Nations Development Program. (2018), GDP per year from World Bank. (2018), and suicide information from Suicide in the Twenty-First Century [dataset] and World Health Organization. (2018). Suicide prevention. The purpose of the data set is to find reasons for the increase in suicide rates associated with socio-economic level in different cohorts around the world from 1985 to 2016. We analyze the dataset to find signals and give advice to prevent suicide.

# The planned analyses / visualizations / coding challenges

# The planned timeline
