<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Final report</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/journal.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.9.0/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-1.46.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-1.46.1/plotly-latest.min.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 61px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h2 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h3 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h4 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h5 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h6 {
  padding-top: 66px;
  margin-top: -66px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="screenshot.html">Introduction</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Suicide Situation
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="world_suicide.html">Worldwide</a>
    </li>
    <li>
      <a href="https://fduxj.shinyapps.io/state/">USA</a>
    </li>
  </ul>
</li>
<li>
  <a href="scatter_plot.html">Regression</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="screenshot.mp4">
    <span class="fa fa fa fa-camera"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/ys3298/life_saver.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="mailto:&lt;ys3298@cumc.columbia.edu.com&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Final report</h1>

</div>


<div id="motivation" class="section level1">
<h1>Motivation</h1>
<div id="some-facts-about-suicide" class="section level2">
<h2>Some facts about suicide</h2>
<ul>
<li><p>About 800,000 people died by suicide every year, which accounts for 1.4% of all deaths worldwide.</p></li>
<li><p>The annual U.S. suicide rate increased by 10% between 2014 and 2017 according to the CDC’s National Center for Health Statistics(NCHS).</p></li>
<li><p>In 2015, suicide has become the second leading cause of death among 15-34 age group and the third leading cause of death among 10-14 age group in the U.S.</p></li>
<li><p>It is reported that in 2016 suicide was the 10th leading cause of death in the U.S., imposing a cost of $69 billion annually.</p></li>
</ul>
<p>On the one hand, almost all the risk factors for suicide are preventable. Usually, people are not aware of the risk factors of suicide and situate themselves in the dangerous environment. We believe that a better understanding of potential risk factors is essential for the prevention of suicide.</p>
<pre class="r"><code>usa_suicide = 
  read_xlsx(&quot;./data/suicide_age_gender.xlsx&quot;) %&gt;% 
  janitor::clean_names() %&gt;% 
  filter(is.na(ten_year_age_groups)) %&gt;% 
  drop_na(gender) %&gt;% 
  select(year, state, gender, deaths, population) %&gt;% 
  group_by(year) %&gt;% 
  summarize(
    deaths = sum(deaths),
    population = sum(population)
  ) %&gt;% 
  mutate(
    suicide_rate = deaths * 100000/population
  ) %&gt;% 
  select(year,suicide_rate)

global_suicide = 
  read_csv(&quot;./data/master.csv&quot;) %&gt;% 
  janitor::clean_names() %&gt;% 
  filter(year &gt;= 1999) %&gt;% 
  group_by(year) %&gt;% 
  summarize(
    deaths = sum(suicides_no),
    population = sum(population)
  ) %&gt;% 
  mutate(
    suicide_global = deaths*100000/population
  ) %&gt;% 
  select(year, suicide_global)

suicide_rate = 
  left_join(usa_suicide, global_suicide, by = &quot;year&quot;) %&gt;% 
  rename( &quot;USA&quot; = &quot;suicide_rate&quot;,  &quot;Global&quot; = &quot;suicide_global&quot;) %&gt;% 
  pivot_longer(
    USA:Global,
    names_to = &quot;region&quot;,
    values_to = &quot;suicide_rate&quot;
  )

suicide_rate %&gt;% 
  ggplot(aes(x = year, y = suicide_rate, color = region)) +
  geom_point() + geom_line() +
  labs(
    title = &quot;1999-2017 Suicide Rate in the U.S. and global&quot;,
    x = &quot;Year&quot;,
    y = &quot;Suicides per 100k&quot;
  )</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>On the other hand, the suicide rate in the U.S. increases overtime while it decreases globally. Therefore, we want to focus on the U.S. to explore the risk factors and promote effective preventive measures.</p>
</div>
<div id="goal-of-our-project" class="section level2">
<h2>Goal of our project</h2>
<ul>
<li><p>Visualizing the general situation of suicide rate worldwide</p></li>
<li><p>Exploring risk factors for suicide in U.S.</p></li>
<li><p>Visualizing the distribution of risk factors and suicide in the U.S.</p></li>
<li><p>Analyzing correlations of these risk factors with suicide in U.S.</p></li>
</ul>
</div>
</div>
<div id="related-work" class="section level1">
<h1>Related Work</h1>
<p>We are inspired to work on this project given our collective interest in suicide in America and the role of data science for exploratory data analysis. Through the project in <a href="https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016">Kaggle</a>, we are aware that suicide has associations with many preventable risk factors. In the meantime, we find that the suicide rate in the U.S. increases at an unprecedented speed.</p>
<p>Therefore, we created this website to develop interactive visualization of suicide rate and potential risk factors. These would be easy to understand for people at risk and help them increase awareness of danger related to suicide and could take action to prevent suicide.</p>
</div>
<div id="initial-question" class="section level1">
<h1>Initial Question</h1>
<p>We aim to investigate the risk factors for suicide and suicide rate in the U.S.. We want to visualize the association and data innovatively and interactively. As stated above, our questions are as follows:</p>
<ul>
<li><p>What are potential risk factors for suicide? How could we visualize the association between these factors and suicide rate?</p></li>
<li><p>How could we use shiny to visualize the distribution of risk factors and suicide rate in the USA?</p></li>
<li><p>Could the model be generalized to other regions? How can we predict suicide rate using the constructed model?</p></li>
</ul>
</div>
<div id="tidy-the-data" class="section level1">
<h1>Tidy the Data</h1>
<div id="data-import" class="section level2">
<h2>Data Import</h2>
<p><strong>Worldwide Suicide Data</strong></p>
<ul>
<li>World suicide data is from <a href="https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016">here</a>, a Kaggle project dataset, including variables such as countries, year, sex, age, suicide number, population and GDP, which aims to describe the general suicide rates among different countries, time, gender and age. The dataset is a complied dataset, coming from <a href="http://hdr.undp.org/en/indicators/137506">United Nations Development Program</a>, <a href="http://hdr.undp.org/en/indicators/137506">World Banlk</a>, <a href="https://www.kaggle.com/szamil/suicide-in-the-twenty-first-century/notebook">Suicide in the 21st Century</a> and <a href="http://www.who.int/mental_health/suicide-prevention/en/">World Health Organization</a></li>
</ul>
<p><strong>USA Suicide Data and the potential risk factors data</strong></p>
<ul>
<li><p>The suicide rates of each state from 1999 to 2017 is from <a href="./data/suicide_age_gender.xlsx">Domectis suicide distribution dataset</a> from CDC. This dataset also includes gender and age composition in each state as well as suicide rates among groups.</p></li>
<li><p>The per capital GDP of each state in 2007 is from <a href="https://en.wikipedia.org/wiki/List_of_U.S._states_by_GDP_per_capita">Wiki</a>, presenting a list of U.S states sorted by their gross domestic product (GDP) per capita from 2011-2018.</p></li>
<li><p>The average yearly precipitation of each state is from <a href="https://www.netstate.com/states/tables/state_precipitation.htm">NETSTATE.COM</a>, presenting a list of U.S. states sorted by their average yearly precipitation.</p></li>
<li><p>The average temperature of each state is from <a href="http://www.usa.com/rank/us--average-temperature--metro-area-rank.htm?yr=9000&amp;dis=&amp;wist=&amp;plow=&amp;phigh=">USA.COM</a>, presenting a list of U.S. areas sorted by their average temperature.</p></li>
<li><p>The marijuana data of each state is from <a href="https://www.samhsa.gov/data/sites/default/files/cbhsq-reports/NSDUHsaePercentsExcelCSVs2017/NSDUHsaePercents2017.pdf">samhsa.gov</a>, showing the percentage of U.S. adults that have used cannabis within the past year from 2016 to 2017, by state.</p></li>
<li><p>The alcohol consumption data of each state is from <a href="https://www.openicpsr.org/openicpsr/project/105583/version/V3/view;jsessionid=F62F155BFF788FAB14D58B1EF8FFF774">NIH; NIAAA</a>, showing apparent per capita alcohol consumption: national, state, and regional trends in 1977-2017. We only select 2007 data.</p></li>
<li><p>The education attainment data of each state is from <a href="https://ssti.org/blog/useful-stats-educational-attainment-across-states-2000-2017">SSTi</a>, containing information on share of population with advanced degree, bachelor’s degree, associate’s or some college, and high school or less.</p></li>
<li><p>The education attainment data of each state is from <a href="https://ssti.org/blog/useful-stats-educational-attainment-across-states-2000-2017">SSTi</a>, containing information on share of population with advanced degree, bachelors’ degree, associate’s or some college, and high school or less.</p></li>
<li><p>The gun data of each state is from <a href="https://www.thoughtco.com/gun-owners-percentage-of-state-populations-3325153">ThoughtCo</a> containing information on number of guns per capita and total guns registered of each state in 2017.</p></li>
</ul>
<p>All the data can be found <a href="https://github.com/ys3298/life_saver.github.io/tree/master/data">here</a>.</p>
</div>
<div id="data-cleaning" class="section level2">
<h2>Data Cleaning</h2>
<p><strong>Worldwide Suicide Data</strong></p>
<pre class="r"><code>## global map
world &lt;- read_csv(&quot;./data/master.csv&quot;)
world_clean &lt;-
  world %&gt;% 
  rename( &quot;rate_standardized&quot; = &quot;suicides/100k pop&quot;) %&gt;% 
  mutate(suicides = population * rate_standardized) %&gt;% 
  group_by(country,year) %&gt;% 
  summarise(rate = sum(suicides)/sum(population))

world_clean &lt;-
  world_clean %&gt;% 
  mutate(
    &#39;country_iso3c&#39; =   countrycode(country,&#39;country.name&#39;, &#39;iso3c&#39;)
  )

# get Min and Max values of suicide rate
vmax &lt;- world_clean %&gt;% pull(rate) %&gt;% max(na.rm=T)
vmin &lt;- world_clean %&gt;% pull(rate) %&gt;% min(na.rm=T)
## Global total trend (by year)

data_year=global %&gt;% 
  group_by(year) %&gt;%
  summarize(population = sum(population), 
            suicides = sum(suicides_no), 
            suicides_per100k = (suicides / population) * 100000)

data_year2=arrange(data_year, desc(suicides_per100k))[1,] 
data_year2$suicides_per100k&lt;-round(data_year2$suicides_per100k,2)

## Global gender trend

data_gender=global %&gt;%
  group_by(sex,year) %&gt;%
  summarize(population = sum(population), 
            suicides = sum(suicides_no), 
            suicides_per100k = (suicides / population) * 100000)
## Different age group trend(by year) animation separeted line

data_age=global %&gt;% 
  mutate(
    age=fct_relevel(age,&quot;5-14 years&quot;,&quot;15-24 years&quot;,&quot;25-34 years&quot;,&quot;35-54 years&quot;,&quot;55-74 years&quot;,&quot;75+ years&quot;)
  )%&gt;%
  group_by(year, age) %&gt;%
  summarize(suicide_per100k = (sum(as.numeric(suicides_no)) / sum(as.numeric(population))) * 100000) 
## average suicide rate ranking during 1987-2016 in different continet

global_rank=global %&gt;%
  filter(year&gt;2010) %&gt;% 
  group_by(country) %&gt;% 
  summarize(suicide_per100k = (sum(as.numeric(suicides_no)) / sum(as.numeric(population))) * 100000) %&gt;% 
  arrange(desc(suicide_per100k)) %&gt;% 
  ungroup() %&gt;% 
  mutate(
    country=as.factor(country),
    country=fct_reorder(country,desc(suicide_per100k))
  ) %&gt;% 
  head(40) %&gt;% 
  mutate(highlight_flag = ifelse(country == &#39;United States&#39;, T, F))</code></pre>
<p>We directly downloaded the csv file of world suicide data <a href="https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016">here</a>. Then we calculated suicide rate per 100k using suicide number and total population. Next, for different purposes, we <code>group_by</code> different variables such as year, country and gender to get the rates in different groups.</p>
<p><strong>US_2017 Data</strong></p>
<pre class="r"><code>## suicide_rate_df
suicide_rate_df = 
  read_excel(&quot;./data/suicide_age_gender.xlsx&quot;) %&gt;% 
  janitor::clean_names() %&gt;%
  filter(year == 2017) %&gt;% 
  filter(is.na(ten_year_age_groups)) %&gt;% 
  drop_na(gender) %&gt;% 
  select(state,gender, deaths, population) %&gt;%
  group_by(state) %&gt;% 
  summarize(
    suicide_rate_per100000 = sum(deaths)*100000/sum(population)
  )


## gender_rate_df
gender_rate_df = 
  read_excel(&quot;./data/suicide_age_gender.xlsx&quot;) %&gt;% 
  janitor::clean_names() %&gt;%
  filter(year == 2017) %&gt;% 
  filter(is.na(ten_year_age_groups)) %&gt;% 
  drop_na(gender) %&gt;% 
  select(state,gender,population) %&gt;% 
  pivot_wider(
    names_from = &quot;gender&quot;,
    values_from = &quot;population&quot;
  ) %&gt;% 
  mutate(
    female_ratio = Female/(Female+Male),
    male_ratio = Male/(Female+Male)
  ) %&gt;% 
  select(state, female_ratio, male_ratio)


## gender_suiciderate_df
gender_suiciderate_df =
  read_excel(&quot;./data/suicide_age_gender.xlsx&quot;) %&gt;% 
  janitor::clean_names() %&gt;%
  filter(year == 2017) %&gt;% 
  filter(is.na(ten_year_age_groups)) %&gt;% 
  drop_na(gender) %&gt;% 
  select(state,gender,deaths,population) %&gt;% 
  mutate(
    suicide_rate_per100000 = deaths*100000/population
  ) %&gt;% 
  select(state, gender, suicide_rate_per100000) %&gt;% 
  pivot_wider(
    names_from = gender,
    values_from = suicide_rate_per100000
  ) %&gt;% 
  mutate(F_suicide_rate_per100000 = Female, M_suicide_rate_per100000 = Male) %&gt;% 
  select(-Female, -Male)


## age 
age_df =
  read_excel(&quot;./data/suicide_age_gender.xlsx&quot;) %&gt;% 
  janitor::clean_names() %&gt;%
  filter(year == 2017) %&gt;% 
  drop_na(ten_year_age_groups) %&gt;% 
  select(state,gender,ten_year_age_groups, population) %&gt;% 
  pivot_wider(
    names_from = &quot;gender&quot;,
    values_from = &quot;population&quot;
  ) %&gt;% 
  mutate(
    Female = replace(Female, is.na(Female), 0),
    Male = replace(Male, is.na(Male), 0),
    total = Female + Male
  ) %&gt;% 
  select(-Female, -Male) %&gt;%
  pivot_wider(
    names_from = &quot;ten_year_age_groups&quot;,
    values_from = &quot;total&quot;
  ) %&gt;%
  rename(&quot;Y15_24&quot; = &quot;15-24 years&quot;, &quot;Y25_34&quot; = &quot;25-34 years&quot;,&quot;Y35_44&quot; = &quot;35-44 years&quot;,&quot;Y45_54&quot; = &quot;45-54 years&quot;,&quot;Y55_64&quot; = &quot;55-64 years&quot;,&quot;Y65_74&quot; = &quot;65-74 years&quot;,&quot;Y5_14&quot; = &quot;5-14 years&quot;, &quot;Y75_84&quot; = &quot;75-84 years&quot;,&quot;Y85_larger&quot; = &quot;85+ years&quot;) %&gt;% 
  mutate(
    Y5_14 = replace(Y5_14, is.na(Y5_14), 0),
    Y15_24 = replace(Y15_24, is.na(Y15_24), 0),
    Y25_34 = replace(Y25_34, is.na(Y25_34), 0),
    Y35_44 = replace(Y35_44, is.na(Y35_44), 0),
    Y45_54 = replace(Y45_54, is.na(Y45_54), 0),
    Y55_64 = replace(Y55_64, is.na(Y55_64), 0),
    Y65_74 = replace(Y65_74, is.na(Y65_74), 0),
    Y75_84 = replace(Y75_84, is.na(Y75_84), 0),
    Y85_larger = replace(Y85_larger, is.na(Y85_larger), 0),
    total = Y5_14 + Y15_24 + Y25_34+Y35_44+Y45_54+Y55_64+Y65_74 +Y75_84+Y85_larger,
    R5_14 = Y5_14/total,
    R15_24= Y15_24/total,
    R25_34=Y25_34/total,
    R35_44=Y35_44/total,
    R45_54=Y45_54/total,
    R55_64=Y55_64/total,
    R65_74=Y65_74/total,
    R75_84=Y75_84/total,
    R85_larger = Y85_larger/total
  ) %&gt;% 
  select(state, contains(&quot;R&quot;))


## read and clean alcohol
alcohol = read_excel(&quot;./data/alcohol2017.xlsx&quot;, sheet = 2, skip = 3) %&gt;% 
  janitor::clean_names() %&gt;% 
  remove_missing() %&gt;% 
  mutate(state = alcohol_consumption_per_capita_from_all_beverages_in_the_u_s_in_2017_by_state_in_gallons_of_ethanol, 
         alcohol_consumption_per_capita_gallons = x2) %&gt;% 
  select(state, alcohol_consumption_per_capita_gallons)


## read and clean marijuana
marijuana = read_excel(&quot;./data/marijuana2017.xlsx&quot;, sheet = 2, skip = 3) %&gt;% 
  janitor::clean_names() %&gt;% 
  remove_missing() %&gt;% 
  mutate(state = percentage_of_u_s_adults_that_have_used_cannabis_within_the_past_year_from_2016_to_2017_by_state, 
         marijuana_percentage = x2*0.01) %&gt;% 
  select(state, marijuana_percentage)

left_join(alcohol, marijuana)


## education
edu = 
  cbind(readxl::read_excel(&quot;./xj/Educational Attainment.xlsx&quot;,range = &quot;A2:A54&quot;),
        readxl::read_excel(&quot;./xj/Educational Attainment.xlsx&quot;,range = &quot;N2:S54&quot;)) %&gt;% 
  janitor::clean_names() %&gt;% 
  mutate(year = &quot;2017&quot;) %&gt;% 
  select(state, year, everything(),-less_than_bachelors,-at_least_bachelors) 


## gun
url = &quot;https://www.thoughtco.com/gun-owners-percentage-of-state-populations-3325153&quot;
gun_xml = read_html(url)
gun_xml %&gt;%
  html_nodes(css = &quot;table&quot;)

gun= 
  (gun_xml %&gt;% html_nodes(css = &quot;table&quot;)) %&gt;% 
  .[[1]] %&gt;%
  html_table(header = T) %&gt;% 
  slice(-1) %&gt;% 
  as_tibble() %&gt;% 
  janitor::clean_names() %&gt;% 
  mutate(year = &quot;2017&quot;) %&gt;% 
  select(state,year,everything(),-rank) %&gt;% 
  select(-year)


## precipitation
precipitation = read_html(&quot;https://www.netstate.com/states/tables/state_precipitation.htm&quot;) %&gt;%
  html_nodes(css = &quot;table&quot;) %&gt;%
  .[[1]] %&gt;%
  html_table(fill = TRUE) %&gt;% 
  select(X2, X3) %&gt;% 
  slice(-1:-4) %&gt;% 
  slice(-(n() - 3):-n()) %&gt;% 
  rename(state = X2, precipitation = X3) %&gt;% 
  separate(precipitation, into = c(&quot;precipitation_inches&quot;, &quot;precipitation_cm&quot;), sep = &quot; inches [(]&quot;) %&gt;% 
  select(state, precipitation_inches) %&gt;% 
  mutate(precipitation_inches = as.numeric(precipitation_inches))


## temperature
temp_data = read_html(&quot;http://www.usa.com/rank/us--average-temperature--metro-area-rank.htm?yr=9000&amp;dis=&amp;wist=&amp;plow=&amp;phigh=&quot;) %&gt;%
  html_nodes(css = &quot;table&quot;) %&gt;%
  .[[2]] %&gt;%
  html_table() %&gt;% 
  slice(-1) %&gt;% 
  separate(X2, into = c(&quot;temperature&quot;, &quot;unit&quot;), sep = &quot;°&quot;) %&gt;% 
  separate(X3, into = c(&quot;area_state&quot;, &quot;population&quot;), sep = &quot; / &quot;) %&gt;% 
  separate(area_state, into = c(&quot;area&quot;, &quot;state_ab&quot;), sep = &quot;, &quot;) %&gt;% 
  select(temperature, state_ab) %&gt;% 
  mutate(temperature = as.numeric(temperature)) %&gt;% 
  group_by(state_ab) %&gt;% 
  summarize(mean_temperature_F = mean(temperature)) %&gt;% 
  filter(nchar(state_ab) == 2)

state_ab_data = read_excel(path = &quot;./data/state_ab.xlsx&quot;)

temperature = 
  left_join(state_ab_data, temp_data, by = &quot;state_ab&quot;) %&gt;% 
  select(state, mean_temperature_F) %&gt;% 
  mutate(state = str_replace(state, &quot;\\s&quot;, &quot;&quot;))

## GDP
gdp = read.csv(&quot;./data/gdp_2017.csv&quot;) %&gt;% 
  mutate(gdp = X2017) %&gt;% 
  select(-X2017)

## joint

us_2017 = 
  left_join(suicide_rate_df, gender_rate_df) %&gt;% 
  left_join(gender_suiciderate_df) %&gt;% 
  left_join(age_df) %&gt;% 
  left_join(alcohol) %&gt;% 
  left_join(marijuana) %&gt;% 
  left_join(edu) %&gt;% 
  left_join(gdp) %&gt;% 
  left_join(gun) %&gt;% 
  left_join(precipitation) %&gt;% 
  left_join(temperature) %&gt;% 
  select(-year) %&gt;% 
  select(-Y85_larger) 

names(us_2017) = c(&quot;State&quot;, 
                   &quot;Suicide rate&quot;, &quot;Female proportion&quot;, &quot;Male proportion&quot;,
                   &quot;Female Suicide rate&quot;, &quot;Male Suicide rate&quot;, 
                   &quot;Age 5-14&quot;,&quot;Age 15-24&quot;, &quot;Age 25-34&quot;, &quot;Age 35-44&quot;, &quot;Age 45-54&quot;, &quot;Age 55-64&quot;, &quot;Age 65-74&quot;, &quot;Age 75-84&quot;, &quot;Age &gt;85&quot;,
                   &quot;Alcohol consumption&quot;, &quot;Marijuana usage&quot;, 
                   &quot;Advanced degree&quot;, &quot;Bachelors degree&quot;, &quot;College&quot;, &quot;Below college degree&quot;,
                   &quot;GDP&quot;, &quot;Guns number per capita(average)&quot;, &quot;Guns number registered(average)&quot;, &quot;Precipitation&quot;, &quot;Temperature&quot;
                   )

# write_csv(us_2017,&quot;./data/us_2017.csv&quot;)</code></pre>
<p>After we got USA Suicide Data and the potential risk factors data, we did some data cleaning process. We collected data by downloading directly or extracting tables using <code>read_html</code> function from the website. Then, we selected states and risk factor information in 2017 and joined every data frame together to get the final merged dataset.</p>
</div>
<div id="final-combined-dataset-of-usa-suicide-and-risk-factors" class="section level2">
<h2>Final Combined Dataset of USA suicide and risk factors</h2>
<p>After collecting data from different sources, we constructed a <a href="./data/US_2017.csv">merged dataset</a> collecting multiple potential risk factors for suicide rate in different states in the U.S., here are the descriptions:</p>
<p><strong>Suicide rate (2017)</strong>: The number of suicide deaths cases per 100k population.</p>
<p><strong>Female proportion (2017)</strong>: The proportion of female.</p>
<p><strong>Male proportion (2017)</strong>: The proportion of male.</p>
<p><strong>Female Suicide rate (2017)</strong>: The number of female suicide deaths cases per 100k females.</p>
<p><strong>Male Suicide rate (2017)</strong>: The number of male suicide deaths cases per 100k males.</p>
<p><strong>Age 5-14 (2017)</strong>: The proportion of people aged between 5-14.</p>
<p><strong>Age 15-24 (2017)</strong>: The proportion of people aged between 15-24.</p>
<p><strong>Age 25-34 (2017)</strong>: The proportion of people aged between 25-34.</p>
<p><strong>Age 35-44 (2017)</strong>: The proportion of people aged between 35-44.</p>
<p><strong>Age 45-54 (2017)</strong>: The proportion of people aged between 45-54.</p>
<p><strong>Age 55-64 (2017)</strong>: The proportion of people aged between 55-64.</p>
<p><strong>Age 65-74 (2017)</strong>: The proportion of people aged between 65-74.</p>
<p><strong>Age 75-84 (2017)</strong>: The proportion of people aged between 75-84.</p>
<p><strong>Age &gt;85 (2017)</strong>: The proportion of people aged over 85.</p>
<p><strong>Alcohol consumption (2017)</strong>: Alcohol consumption per capita in gallons</p>
<p><strong>Marijuana usage (2017)</strong>: The proportion of people using marijuana.</p>
<p><strong>Advanced degree (2017)</strong>: The proportion of people with advanced degrees.</p>
<p><strong>Bachelors degree(2017)</strong>: The proportion of people with Bachelor’s degrees.</p>
<p><strong>College degree (2017)</strong>: The proportion of people with College degrees.</p>
<p><strong>Below college degree (2017)</strong>: The proportion of people with below college degrees.</p>
<p><strong>GDP (2017)</strong>: Gross Domestic Product per capita.</p>
<p><strong>Guns number per capita (2017)</strong>: Averaged guns number per capita.</p>
<p><strong>Guns number registered (2017)</strong>: Averaged guns number registered</p>
<p><strong>Precipitation</strong>: Averaged Precipitation in inches.</p>
<p><strong>Temperature</strong>: Averaged Temperature in F.</p>
<p>Another dataset we used is <a href="./data/suicide_age_gender.xlsx">Domectis suicide distribution dataset</a> from 1999 to 2017. In this dataset, we have information about number of suicide cases in different years, states, gender and age group and the population in each groups. Using this dataset, we can analyze how suicide cases change in each state in time and how suicide cases distributed in different gender and age groups.</p>
</div>
</div>
<div id="sub-analyses" class="section level1">
<h1>Sub-analyses</h1>
<div id="world-level-insight" class="section level2">
<h2>World-level insight</h2>
<p>Visualizing the world data helps us to understand the general trend of suicide rate among different age, gender and capture the difference between domestic and global suicide rate situation.</p>
<p>Firstly, we drew an animated world map Gif to show the suicide rate change of each country from 1986-2016.</p>
<p>Secondly, the line plot was made to show the annual global suicide rate change. We can tell that before 1995, a dramatic increase happened and after 1995, a steady drop followed.</p>
<p>Thirdly, the global suicide rate change by gender was presented. Generally, the rate in male was much higher than the rate in female.</p>
<p>What’s more, different trends in different age groups showed that 75+ age group occupied the highest position all the time. But all age groups were experiencing a drop from 2000 to 2016.</p>
<p>Finally, the average suicide ranking plot(2010-2016) told us how did America’s suicide rate compare with other countries. In top 40, USA ranked 23rd, indicating a worrying situation.</p>
<p>The detailed analysis can be found <a href="world_suicide.html">here</a>.</p>
</div>
<div id="us-level-insight" class="section level2">
<h2>US-level insight</h2>
<p>To show how the suicide cases distributed in different states, we made a Crude Suicide Rate map allowing users to toggle between different years (1999-2017) and choose gender, demonstrating the changes in the suicide rate over time and visualize regional differences across the U.S. The map demonstrates that there are significant changes over time and gender.</p>
<p>We made a line plot to show the change of total suicide rate by year in US. We can see a stable increase by year and the fact that there are many more cases of suicide in male than in female.</p>
<pre class="r"><code>abb = read_excel(&quot;./data/state_ab.xlsx&quot;) %&gt;% mutate(state = str_replace(state, &quot;\\s&quot;, &quot;&quot;))

suicide = read_excel(&quot;./data/suicide_age_gender.xlsx&quot;) %&gt;% janitor::clean_names() %&gt;% 
  filter(state != &quot;District of Columbia&quot;) %&gt;% 
  filter(is.na(ten_year_age_groups)) %&gt;% 
  drop_na(gender) %&gt;% 
  left_join(abb) %&gt;% select(year, state_ab, state, gender, deaths, population) %&gt;% 
  mutate(rate = (deaths/population)*100000) %&gt;% 
  select(year, state_ab, gender, rate)


suicide_all = suicide %&gt;% group_by(year,gender) %&gt;% summarise(rate = sum(rate))


line = 
  suicide_all %&gt;%
  ggplot(aes(x = year, y = rate)) + geom_point(aes(color = gender)) + geom_line(aes(color = gender)) + theme_bw() +
  labs(
    title = &quot;Suicide rate change over time in US&quot;
  )

ggplotly(line)</code></pre>
<div id="htmlwidget-f1ab7b781d42248cf55e" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-f1ab7b781d42248cf55e">{"x":{"data":[{"x":[1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017],"y":[222.745064751594,213.555356518198,233.178484315938,230.873680909311,234.055292563318,252.909367669512,244.111343326498,256.864897480587,257.85519337019,274.619879251796,274.469445235843,289.588869183436,302.749819254446,309.970945203122,316.808421185081,334.886141643324,361.859755678404,356.572946465376,366.083530154266],"text":["gender: Female<br />year: 1999<br />rate:  222.7451","gender: Female<br />year: 2000<br />rate:  213.5554","gender: Female<br />year: 2001<br />rate:  233.1785","gender: Female<br />year: 2002<br />rate:  230.8737","gender: Female<br />year: 2003<br />rate:  234.0553","gender: Female<br />year: 2004<br />rate:  252.9094","gender: Female<br />year: 2005<br />rate:  244.1113","gender: Female<br />year: 2006<br />rate:  256.8649","gender: Female<br />year: 2007<br />rate:  257.8552","gender: Female<br />year: 2008<br />rate:  274.6199","gender: Female<br />year: 2009<br />rate:  274.4694","gender: Female<br />year: 2010<br />rate:  289.5889","gender: Female<br />year: 2011<br />rate:  302.7498","gender: Female<br />year: 2012<br />rate:  309.9709","gender: Female<br />year: 2013<br />rate:  316.8084","gender: Female<br />year: 2014<br />rate:  334.8861","gender: Female<br />year: 2015<br />rate:  361.8598","gender: Female<br />year: 2016<br />rate:  356.5729","gender: Female<br />year: 2017<br />rate:  366.0835"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(248,118,109,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)"}},"hoveron":"points","name":"Female","legendgroup":"Female","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(248,118,109,1)","dash":"solid"},"frame":null},{"x":[1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017],"y":[972.433194943466,975.662885529269,998.211844685336,1023.88633539761,1009.076380181,1012.49467644936,1014.43447283582,1018.61077204747,1042.67730669679,1076.56869614423,1085.34692077021,1143.0782276773,1143.1410954919,1186.013807026,1185.20638429768,1214.21784648891,1244.93606028268,1260.34554535054,1345.58373285145],"text":["gender: Male<br />year: 1999<br />rate:  972.4332","gender: Male<br />year: 2000<br />rate:  975.6629","gender: Male<br />year: 2001<br />rate:  998.2118","gender: Male<br />year: 2002<br />rate: 1023.8863","gender: Male<br />year: 2003<br />rate: 1009.0764","gender: Male<br />year: 2004<br />rate: 1012.4947","gender: Male<br />year: 2005<br />rate: 1014.4345","gender: Male<br />year: 2006<br />rate: 1018.6108","gender: Male<br />year: 2007<br />rate: 1042.6773","gender: Male<br />year: 2008<br />rate: 1076.5687","gender: Male<br />year: 2009<br />rate: 1085.3469","gender: Male<br />year: 2010<br />rate: 1143.0782","gender: Male<br />year: 2011<br />rate: 1143.1411","gender: Male<br />year: 2012<br />rate: 1186.0138","gender: Male<br />year: 2013<br />rate: 1185.2064","gender: Male<br />year: 2014<br />rate: 1214.2178","gender: Male<br />year: 2015<br />rate: 1244.9361","gender: Male<br />year: 2016<br />rate: 1260.3455","gender: Male<br />year: 2017<br />rate: 1345.5837"],"type":"scatter","mode":"markers+lines","marker":{"autocolorscale":false,"color":"rgba(0,191,196,1)","opacity":1,"size":5.66929133858268,"symbol":"circle","line":{"width":1.88976377952756,"color":"rgba(0,191,196,1)"}},"hoveron":"points","name":"Male","legendgroup":"Male","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","line":{"width":1.88976377952756,"color":"rgba(0,191,196,1)","dash":"solid"},"frame":null}],"layout":{"margin":{"t":43.7625570776256,"r":7.30593607305936,"b":40.1826484018265,"l":48.9497716894977},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"title":{"text":"Suicide rate change over time in US","font":{"color":"rgba(0,0,0,1)","family":"","size":17.5342465753425},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[1998.1,2017.9],"tickmode":"array","ticktext":["2000","2005","2010","2015"],"tickvals":[2000,2005,2010,2015],"categoryorder":"array","categoryarray":["2000","2005","2010","2015"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":{"text":"year","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[156.953937701535,1402.18515166811],"tickmode":"array","ticktext":["500","1000"],"tickvals":[500,1000],"categoryorder":"array","categoryarray":["500","1000"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":{"text":"rate","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895},"y":0.913385826771654},"annotations":[{"text":"gender","x":1.02,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"left","yanchor":"bottom","legendTitle":true}],"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","showSendToCloud":false},"source":"A","attrs":{"98d376e681a0":{"colour":{},"x":{},"y":{},"type":"scatter"},"98d317486c5c":{"colour":{},"x":{},"y":{}}},"cur_data":"98d376e681a0","visdat":{"98d376e681a0":["function (y) ","x"],"98d317486c5c":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>We also made boxplots to show the distributions of suicides cases and population composition in states.</p>
<pre class="r"><code>df = read_csv(&quot;./data/us_2017.csv&quot;) %&gt;% janitor::clean_names() %&gt;% filter(state != &quot;District of Columbia&quot;) %&gt;% 
  pivot_longer(
    2:26,
    names_to = &quot;variables&quot;,
    values_to = &quot;data&quot;
  )

# suicide rate
df1 = read_csv(&quot;./data/us_2017.csv&quot;) %&gt;% janitor::clean_names() %&gt;% filter(state != &quot;District of Columbia&quot; ) %&gt;% select(state,suicide_rate, male_suicide_rate, female_suicide_rate) %&gt;% 
  pivot_longer(
    -state,
    names_to = &quot;variables&quot;,
    values_to = &quot;data&quot;
  ) 
  
  
df1 %&gt;% 
  plot_ly(y = ~data, color = ~variables, type = &quot;box&quot;,
          colors = &quot;Set2&quot;) </code></pre>
<div id="htmlwidget-76d84d45e10c170ae44c" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-76d84d45e10c170ae44c">{"x":{"visdat":{"98d352404f63":["function () ","plotlyVisDat"]},"cur_data":"98d352404f63","attrs":{"98d352404f63":{"y":{},"color":{},"colors":"Set2","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"box"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"yaxis":{"domain":[0,1],"automargin":true,"title":"data"},"xaxis":{"domain":[0,1],"automargin":true},"hovermode":"closest","showlegend":true},"source":"A","config":{"showSendToCloud":false},"data":[{"fillcolor":"rgba(102,194,165,0.5)","y":[5.96442577888442,11.6146321702648,8.78692528193984,9.55362956128555,4.80162501068424,9.98268829486707,5.28211964382177,2.82016417384298,6.82353272373334,6.44393440859251,8.15235342982159,8.40645195187306,4.9773064015995,5.79929183545515,5.88243479668914,8.14417516957336,6.59329669702386,6.63914414333536,8.51204968688866,4.5862394215822,4.56161207937545,6.06892199932827,5.57190616338543,5.65588062061263,7.42455876907887,12.4631617699224,5.61362655869099,10.9751119260652,8.70481243342294,4.44775193260246,10.3422820957069,3.94636198793628,6.50609325033607,7.878422359506,5.49994962584364,9.17661556333831,9.33109450867481,7.07048199261487,5.69174953364375,7.38397684755992,8.5905466838168,7.47089114068589,5.72218825184902,10.6483480451516,9.19464427823628,6.01864665036752,7.96808444548885,9.37598461466339,6.79771143714949,10.2156920074539],"type":"box","name":"female_suicide_rate","marker":{"color":"rgba(102,194,165,1)","line":{"color":"rgba(102,194,165,1)"}},"line":{"color":"rgba(102,194,165,1)"},"xaxis":"x","yaxis":"y","frame":null},{"fillcolor":"rgba(205,181,144,0.5)","y":[29.0274408899602,41.1073651988666,29.0972596688187,32.8576538686669,17.0250208766456,31.8885120926553,17.5819157438064,21.0519984361373,24.2472836851269,21.7712240373228,23.6004842986955,37.1894967563786,18.2440049849995,27.2581108851433,24.6048367357242,29.8218403312497,28.1180758668525,24.5037445740148,33.0012833832427,16.5976291632955,15.6439309204847,23.4310381112259,22.3995136928731,24.6217177382877,30.6438268010909,46.5067037712021,23.065739444815,30.7897129108648,30.9770243710987,13.419539850802,36.9387628802178,13.4163953123758,23.5532260921759,32.2748057702189,24.6976247571371,29.4727459254186,30.6382547592803,24.986729288162,19.0294587672406,26.5415535300471,35.0829232731912,27.7170153780595,21.0072783748132,31.9526051298339,26.601266479809,22.0076813287744,26.974680252833,34.0522133938706,25.219079916385,43.3255031512534],"type":"box","name":"male_suicide_rate","marker":{"color":"rgba(205,181,144,1)","line":{"color":"rgba(205,181,144,1)"}},"line":{"color":"rgba(205,181,144,1)"},"xaxis":"x","yaxis":"y","frame":null},{"fillcolor":"rgba(179,179,179,0.5)","y":[17.1290940842673,27.0345163187099,18.8846780411814,21.0033755187185,10.8759838623669,21.0088754473303,11.2870465951579,11.6431499294654,15.3399668325041,13.9030329610229,15.9015031473768,22.8312762858173,11.4981827481485,16.3796281824403,15.1952928924494,18.9487364591196,17.1972945018723,15.3703846417409,20.5104097815192,10.4094774491889,9.9419532789422,14.6150827855103,13.9511380219438,14.8453470057974,18.827087189533,29.605147297507,14.3223497403228,20.9136705693288,19.734955819764,8.8277973235451,23.5145373478858,8.54433930216225,14.8051977632763,20.3867390881303,14.9074387862223,19.2324130267544,19.8900447429453,15.844708425738,12.1739573571754,16.6787112968813,21.9624545515175,17.3466762279362,13.3158586683237,21.3744582638717,17.7982448685736,13.8842647360927,17.4729260791253,21.5876029885613,15.9607059497888,27.100972700517],"type":"box","name":"suicide_rate","marker":{"color":"rgba(179,179,179,1)","line":{"color":"rgba(179,179,179,1)"}},"line":{"color":"rgba(179,179,179,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<pre class="r"><code># population proportion

df2 = read_csv(&quot;./data/us_2017.csv&quot;) %&gt;% janitor::clean_names() %&gt;% filter(state != &quot;District of Columbia&quot; ) %&gt;% 
  select(state, male_proportion, female_proportion,
         age_5_14,age_15_24,age_25_34,age_35_44,age_45_54,age_55_64,age_65_74,age_75_84,age_85,advanced_degree,bachelors_degree,college,below_college_degree) %&gt;% 
  pivot_longer(
    -state,
    names_to = &quot;variables&quot;,
    values_to = &quot;data&quot;
  ) %&gt;% 
  mutate(variables = factor(variables, levels = c(&quot;male_proportion&quot;, &quot;female_proportion&quot;,
         &quot;age_5_14&quot;,&quot;age_15_24&quot;,&quot;age_25_34&quot;,&quot;age_35_44&quot;,&quot;age_45_54&quot;,&quot;age_55_64&quot;,&quot;age_65_74&quot;,&quot;age_75_84&quot;,&quot;age_85&quot;,&quot;advanced_degree&quot;,&quot;bachelors_degree&quot;,&quot;college&quot;,&quot;below_college_degree&quot;)) 
  ) %&gt;% 
  mutate(
    types = case_when(
      variables %in% c(&quot;male_proportion&quot; , &quot;female_proportion&quot;) ~ &quot;Gender&quot;,
      variables %in% c(&quot;age_5_14&quot;,&quot;age_15_24&quot;,&quot;age_25_34&quot;,&quot;age_35_44&quot;,&quot;age_45_54&quot;,&quot;age_55_64&quot;,&quot;age_65_74&quot;,&quot;age_75_84&quot;,&quot;age_85&quot;) ~ &quot;Age&quot;,
      variables %in% c(&quot;advanced_degree&quot;,&quot;bachelors_degree&quot;,&quot;college&quot;,&quot;below_college_degree&quot;) ~ &quot;Education&quot;))

boxplot = 
  df2 %&gt;% 
  ggplot(aes(x = variables, y = data)) + geom_boxplot(aes(color = types)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(
    x = &quot;population compostion&quot;,
    y = &quot;proportion&quot;,
    title = &quot;population compostion&quot;
  ) 

ggplotly(boxplot)</code></pre>
<div id="htmlwidget-93d2a300041ecd9e4638" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-93d2a300041ecd9e4638">{"x":{"data":[{"x":[3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11],"y":[0.1578244377201,0,0,0,0,0,0,0,0.076114369792137,0.0636630774584533,0,0.0823538323416645,0.0772520288100954,0,0,0.136439036787666,0,0.0767999885568433,0,0,0,0,0,0,0.0757806879277514,0,0,0,0,0.074597106675867,0,0,0,0.0673364769318084,0,0.0738907276740256,0,0,0,0,0,0,0,0,0,0,0,0.0714809760136162,0,0,0.132210590382078,0.157345879878569,0.154359979410732,0.174684598220895,0.159992022905657,0.201617600338875,0.17376555393485,0.174089982970999,0.111723218778976,0.143812838694256,0.104829006215081,0.158688833039771,0.177314854641028,0.174539397390269,0.164760906091068,0.153597009434529,0.126998236058931,0.171453667666756,0.158751388302282,0.153925104262955,0.164588589363383,0.106249261069347,0.157545144833997,0.0871956962566715,0.200617136446339,0.122306167444264,0.167329370033323,0.16544282271237,0.190600270218105,0.231086546590717,0.157097470437882,0.22077592970726,0.151344061966074,0.152013680928135,0.19436583695403,0.155350925116458,0.215613605116863,0.168590236213405,0.173731500188169,0.149763662629047,0.188687361101154,0.154158300842808,0.179085024055471,0.112055831695035,0.180548743302806,0.162444346558756,0.169112064506,0.158622818531737,0.24470053728448,0.176375415632588,0.162518717047878,0.181352099738315,0.15805439261361,0.172207716653109,0.342487998746457,0.166045326489794,0.156705969076426,0.146633575543093,0.105768374963635,0.208043998016513,0.190693464703078,0.183145618585706,0.15719321440338,0.14658303295298,0.160578060875389,0.18526982582212,0.228002998393056,0.168647881698357,0.168144647376035,0.175764974339353,0.285101461117383,0.159962230520808,0.213187008829991,0.172466044740176,0.178641443789257,0.181246006316461,0.173754275067324,0.214447871439161,0.175847123301684,0.163854986782096,0.170067187367267,0.187239379354996,0.153800246574801,0.177586982425959,0.367538441742263,0.120168860836574,0.156164334424469,0.181092500450782,0.105503056420357,0.174468687104049,0.17697190419829,0.187890124417751,0.210236572362222,0.182915328289491,0.162478878145729,0.167263550359616,0.184516889164565,0.171278306949116,0.183283560968199,0.162533721442954,0.14483448274343,0.159497586695209,0.141980330297559,0.159820090018097,0.13862195695218,0.177767261463518,0.169812450187135,0.195968876214563,0.159720222558682,0.156235654239787,0.162289779369866,0.125675970374624,0.0989722055801386,0.140915749947255,0.148200225378681,0.152333068470376,0.170392574789189,0.149596451847949,0.171013494961792,0.162314444488073,0.134613405433646,0.142788399372315,0.150674145197164,0.14486920580645,0.161503092094707,0.150624075146368,0.158365257081885,0.165265617943857,0.161999263103301,0.190011735754307,0.133500317397543,0.164781319754265,0.142979880666013,0.210915749557714,0.174453259096693,0.155487925714124,0.165958627886061,0.168581091788271,0.154209197331771,0.213922905967012,0.141555657130676,0.146230246852941,0.196932666306868,0.162622700972811,0.168051501225639,0.153407485534333,0.160335291349595,0.163620667360464,0.162754381644936,0.160139476640234,0.174584679613261,0.136351334026581,0.155807782116975,0.163144542238495,0.139286887895203,0.140175400305562,0.150429759948237,0.18129923147672,0.152749531295767,0.152154840072272,0.166813661384994,0.147978452667944,0.170707083608126,0.162133339792377,0.162465410371937,0.241564690261334,0.247374720534767,0.183760108686235,0.173713149785158,0.173329694219017,0.178252790702089,0.153195961344364,0.199549269300011,0.153220992728028,0.217158732935633,0.153870171749434,0.158111844479777,0.155513294925372,0.161439961279767,0.135961526088915,0.205253792623141,0.155719032285174,0.164925570370494,0.245052298470603,0.147989273140626,0.166339916942931,0.16354621898727,0.197313476170551,0.158852870052889,0.167373305572213,0.181183863085876,0.15737453518563,0.168893745798401,0.171083580447942,0.154622465103433,0.136280399641922,0.15716216320418,0.182711968696385,0.199888888347409,0.168437725847427,0.148609582844352,0.159212816222382,0.149571294018796,0.18066295351172,0.144364419841176,0.139925560692342,0.166282012649166,0.13994387544337,0.128494806710564,0.150643153797081,0.170849813898922,0.195166080161628,0.161728370535529,0.206617997458435,0.180373381066791,0.105501610999051,0.172584864430553,0.168839460814939,0.170073375041488,0.123975520141778,0.280869367687908,0.166309557035862,0.15433789574233,0.164710828391912,0.181622140115786,0.162748121368901,0.191397804117932,0.175067733955607,0.171330130314187,0.150568970631997,0.171749027803157,0.148348730041,0.200136520387308,0.155275686804349,0.109174310253984,0.165235789788694,0.122401983912305,0.261566092043808,0.202383087253671,0.173795420435218,0.174395025738845,0.160737547148514,0.181135423798926,0.160903994816866,0.198761475612475,0.180779672533795,0.138140006580781,0.168291476397693,0.184414149691896,0.23019118026891,0.0862211770952437,0.100804954550264,0.116787505805341,0.133620794369712,0,0.116821083849791,0.125239363267645,0.082602811925756,0.0994996221688082,0.115976011428798,0.0966841220459508,0.126504287513347,0.0724793033463046,0.100989051485575,0.119175228554007,0.119704834969384,0.113100941658913,0.115251732848678,0.0589190553911822,0.0734588920080312,0.123480416972422,0.118669710845358,0.116830808707819,0.0757556627025776,0.101259735618915,0.0728488110279144,0.10982407565208,0.0802968858166597,0.0586224240415212,0.128310117681185,0.11461252407388,0.131478052166841,0,0.103360387520673,0.137317174233631,0.110164094362901,0.125887160369919,0,0.123985653217261,0.114845010258859,0.123136411111542,0.0858109856158896,0.0448812057183817,0,0.158140120394399,0.111341297333589,0.114640184658401,0.127828059420375,0.122723138533149,0.117585312220584,0.0703884254276995,0.0192072377237996,0.0289074026012482,0.0425403762133368,0.0524031111144043,0.0194443211547155,0.0264240774030371,0.0259009012994155,0,0.0272821231733674,0.0330443073978513,0,0.0246800729024336,0.0601218939529223,0,0.0328584147957801,0.0339307820068952,0.0508577553845686,0.0241900219300659,0,0.0547730214860119,0.0310098554795522,0.0256068476271145,0.0287934913386878,0.0257327670286187,0.0609807357238575,0.0238816078709623,0.0333975163285222,0.044382333679164,0.0258346857957103,0.0546073948901297,0.0264736341512395,0.0207005642134149,0.0575563708211529,0.0246454833658127,0.0640065160218424,0.053268988042272,0.0533263644591121,0.0276821952217587,0.0524194815643582,0,0,0,0.0246632818921395,0.0379756755206947,0.0269306696655294,0,0.0344272165961661,0.050758864035382,0,0.00805470206761071,0.00985718372590045,0,0.00539966131152553,0.00977846891602083,0,0.0121922655043548,0,0.00877185342853012,0.00706066956490975,0.00907414967788719,0.00853866382564295,0.00658570493105393,0.0109123665280716,0.00961154126439964,0.00767309603648625,0.00913663285050081,0,0.00713459025665386,0.0151240008661264,0.00916850202054274,0.00816741628815104,0.00543113058004161,0.0197704096085972,0.00908435977940276,0.00974538675606639,0.00954730898365163,0.0111030151011622,0,0,0.0297018158006462,0.0110952407256887,0,0,0.00893873585435494,0.0107794074997971,0,0.0070827286192198,0,0.00683591820828297,0,0.0089183793383457,0.00757078312848437,0,0,0.00989744653832636,0.00798236954178935,0.0104780133862555,0.00860472733648722,0.00753628584789629],"hoverinfo":"y","type":"box","fillcolor":"rgba(255,255,255,1)","marker":{"opacity":null,"outliercolor":"rgba(0,0,0,1)","line":{"width":1.88976377952756,"color":"rgba(0,0,0,1)"},"size":5.66929133858268},"line":{"color":"rgba(248,118,109,1)","width":1.88976377952756},"name":"Age","legendgroup":"Age","showlegend":true,"xaxis":"x","yaxis":"y","frame":null},{"x":[12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15],"y":[0.179883318638081,0.0804278511181171,0.129500088794482,0.10794558680104,0.186815951264369,0.0896855478516031,0.110000309525099,0.106704560669956,0.0807025975164202,0.11376692492455,0.109454304817675,0.104140988806206,0.0810508820272934,0.085268836482799,0.0789371377349844,0.122030284282831,0.0918804215907216,0.117966368401059,0.146294770282054,0.117312869121941,0.169795794616532,0.0956573892094934,0.101174993145518,0.102769326008925,0.10233887321067,0.10235898151024,0.106776641737754,0.137666835910848,0.153858091420501,0.121836120926901,0.118331258335487,0.117617596606906,0.0778038682568127,0.0983226791187518,0.129371949534948,0.0832065357961488,0.110065458467434,0.0914498615501198,0.093037618014652,0.0828184820136222,0.160643504880065,0.131476933498432,0.147292234744104,0.106442643094506,0.0986350113618714,0.0987938019599695,0.127226511957076,0.14969627768897,0.0788442139193686,0.0956045060232893,0.210063077671754,0.233621239453776,0.222704053664243,0.155796451565861,0.212427868985696,0.203577119274591,0.19215724888739,0.204974591161701,0.151118606283882,0.199035576882745,0.23405855176716,0.132913893505499,0.206116044601723,0.211120723392861,0.153267601725576,0.185543364885792,0.193356265724399,0.165611900271315,0.200679568241497,0.182390527478779,0.182505241700018,0.170810533139126,0.161311112082502,0.171728057575157,0.187127220957932,0.206179332510398,0.175161314947604,0.136265533542808,0.170027699777514,0.188420751154821,0.185738744158068,0.215305578025231,0.218291847453757,0.141344163724903,0.214921581864414,0.198166362934532,0.229664697906373,0.120141613168788,0.195267612668456,0.191516949620965,0.164926034677176,0.174459686529411,0.181742984507017,0.153794881764443,0.203923591156163,0.177680227183402,0.2480031904248,0.214512616835806,0.217407688434873,0.180308192896829,0.288187714149772,0.345042250531013,0.30115549039106,0.312010865138195,0.362736616614142,0.329361758952379,0.289963045834575,0.336179186638159,0.298918983091505,0.338529072068772,0.257141929278681,0.242176162759357,0.231433105347941,0.264855792370633,0.316897432742485,0.245466428818381,0.330972788326897,0.309092152649863,0.278397436613114,0.271651778862388,0.27053309612431,0.28286155033011,0.357879615179139,0.258881023064627,0.338899621914563,0.234761191670477,0.28785186472452,0.293170527418442,0.254671804524355,0.301297241334756,0.316632423376911,0.31924519581649,0.300763692777612,0.290224413502795,0.301637405663464,0.295194186576435,0.318339564369311,0.292365791491883,0.27189876715548,0.292450283769017,0.328890953712307,0.372961038760528,0.326328440046991,0.313920870378749,0.246347917205077,0.338690026970694,0.289147173379939,0.360527844868128,0.36410110780281,0.326461351874401,0.352240651856588,0.439558752576867,0.422719823980512,0.310527855704525,0.487268414771096,0.381069760498494,0.376643509164282,0.30440479795839,0.461072022686421,0.369343671342585,0.348338791736184,0.36334720330038,0.495496704633693,0.417828159859548,0.373130851792647,0.332247896944659,0.351441396275138,0.344364305297994,0.377673455319297,0.546342368387488,0.428793772915031,0.401639902878373,0.470025831999472,0.357262602551172,0.418668078705835,0.437650272877671,0.357904820876579,0.40199524288149,0.361286979843953,0.352536146100041,0.456987337205137,0.387653420454179,0.390298203623467,0.454442674834893,0.395768378040317,0.390553063208498,0.39230795536824,0.417370431604828,0.47892990386776,0.413850283820594,0.455836273593932,0.424623594338074,0.352911674411484,0.371812791170295,0.316675772637358,0.405500911196403,0.414366364366726,0.326040493645577,0.396725879316064,0.35954165669541],"hoverinfo":"y","type":"box","fillcolor":"rgba(255,255,255,1)","marker":{"opacity":null,"outliercolor":"rgba(0,0,0,1)","line":{"width":1.88976377952756,"color":"rgba(0,0,0,1)"},"size":5.66929133858268},"line":{"color":"rgba(0,186,56,1)","width":1.88976377952756},"name":"Education","legendgroup":"Education","showlegend":true,"xaxis":"x","yaxis":"y","frame":null},{"x":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],"y":[0.48409404631666,0.495453925650951,0.501577531179548,0.48480968088012,0.501156998223005,0.491320546460565,0.486006083203808,0.495263089838942,0.497945524571756,0.509978163865945,0.487786450950449,0.512711926109985,0.503531199160775,0.488745356062432,0.486654766309672,0.522836731797322,0.495558775082215,0.495242386216809,0.485488757064873,0.491522160208586,0.496945277588368,0.48517276497805,0.485529158842542,0.484527328172648,0.498419050620245,0.496802462751986,0.490032730319715,0.499006810147098,0.489944285043794,0.501623774638574,0.497173141854575,0.489735729161534,0.488202065282616,0.4922303670303,0.49305305769559,0.503345012460867,0.50474549999655,0.486832864502071,0.491080442533056,0.492641421367616,0.503472624090336,0.488783048359734,0.494271691009642,0.494873770346453,0.491938271692393,0.500081220749896,0.48821353642957,0.483932972880817,0.497417912834332,0.497411173494944,0.504546074349049,0.51178646357043,0.513993916796192,0.487288073890015,0.508679453539435,0.496527375909664,0.477163268202678,0.498422468820452,0.51590595368334,0.504757613783191,0.499918779250104,0.503054722411632,0.504441224917785,0.51482723502195,0.514470841157458,0.512213549049551,0.516067027119183,0.496468800839225,0.509967269680285,0.500993189852902,0.505728308990358,0.502826858145425,0.508061728307607,0.510264270838466,0.511797934717384,0.505126229653546,0.496654987539133,0.502588826505056,0.49525450000345,0.513167135497929,0.503197537248014,0.511216951640266,0.511254643937568,0.513345233690328,0.510055714956206,0.51519031911988,0.498843001776996,0.514511242935127,0.508477839791414,0.504736910161058,0.502054475428244,0.490021836134055,0.515472671827352,0.501580949379755,0.508919557466944,0.507358578632384,0.502582087165668,0.498376225361426,0.50694694230441,0.507769632969699],"hoverinfo":"y","type":"box","fillcolor":"rgba(255,255,255,1)","marker":{"opacity":null,"outliercolor":"rgba(0,0,0,1)","line":{"width":1.88976377952756,"color":"rgba(0,0,0,1)"},"size":5.66929133858268},"line":{"color":"rgba(97,156,255,1)","width":1.88976377952756},"name":"Gender","legendgroup":"Gender","showlegend":true,"xaxis":"x","yaxis":"y","frame":null}],"layout":{"margin":{"t":43.7625570776256,"r":7.30593607305936,"b":90.2069263039479,"l":43.1050228310502},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"title":{"text":"population compostion","font":{"color":"rgba(0,0,0,1)","family":"","size":17.5342465753425},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.4,15.6],"tickmode":"array","ticktext":["male_proportion","female_proportion","age_5_14","age_15_24","age_25_34","age_35_44","age_45_54","age_55_64","age_65_74","age_75_84","age_85","advanced_degree","bachelors_degree","college","below_college_degree"],"tickvals":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],"categoryorder":"array","categoryarray":["male_proportion","female_proportion","age_5_14","age_15_24","age_25_34","age_35_44","age_45_54","age_55_64","age_65_74","age_75_84","age_85","advanced_degree","bachelors_degree","college","below_college_degree"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-45,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"y","title":{"text":"population compostion","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-0.0273171184193744,0.573659486806863],"tickmode":"array","ticktext":["0.0","0.2","0.4"],"tickvals":[0,0.2,0.4],"categoryorder":"array","categoryarray":["0.0","0.2","0.4"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.65296803652968,"tickwidth":0.66417600664176,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.689497716895},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(235,235,235,1)","gridwidth":0.66417600664176,"zeroline":false,"anchor":"x","title":{"text":"proportion","font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(51,51,51,1)","width":0.66417600664176,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.88976377952756,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.689497716895},"y":0.913385826771654},"annotations":[{"text":"types","x":1.02,"y":1,"showarrow":false,"ax":0,"ay":0,"font":{"color":"rgba(0,0,0,1)","family":"","size":14.6118721461187},"xref":"paper","yref":"paper","textangle":-0,"xanchor":"left","yanchor":"bottom","legendTitle":true}],"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","showSendToCloud":false},"source":"A","attrs":{"98d3482ccc4f":{"colour":{},"x":{},"y":{},"type":"box"}},"cur_data":"98d3482ccc4f","visdat":{"98d3482ccc4f":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>To show the distribution of the risk factors, we constructed the U.S. map in shiny app allowing users to choose the types of variables, visualizing regional differences across the U.S. and a bar plot showing the intuitive number in different states. Users can choose TOP N states they want to explore in both plots.</p>
</div>
</div>
<div id="regression-analysis" class="section level1">
<h1>Regression Analysis</h1>
<p>We are interested in whether there is a linear association between suicide rate and some risk factors. We chose <code>suicide</code> as the main outcome, <code>gun</code>, <code>alcohol</code>, <code>temperature</code>, <code>precipitation</code>, <code>marijuana</code>, <code>education</code>, <code>GDP</code> and <code>gender</code> as candidate covariates, each with 50 observations.</p>
<p>One value of <code>gun</code> in Wyoming and one value of <code>temperature</code> in Rhode Island were missing. We replaced them with the mean value of the other 49 observations.</p>
<p>After tidying the <a href="./data/US_2017.csv">merged dataset</a>, we obtained the <a href="./data/regression_data.csv">regression dataset</a>. The description of the dataset is shown below:</p>
<table>
<thead>
<tr class="header">
<th align="center">Variables</th>
<th align="center">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">state</td>
<td align="center">State</td>
</tr>
<tr class="even">
<td align="center">suicide</td>
<td align="center">The number of suicide deaths per 100k population</td>
</tr>
<tr class="odd">
<td align="center">gun</td>
<td align="center">Averaged guns number per capita</td>
</tr>
<tr class="even">
<td align="center">alcohol</td>
<td align="center">Alcohol consumption per capita (gallons of ethanol)</td>
</tr>
<tr class="odd">
<td align="center">temperature</td>
<td align="center">Average temperature (F)</td>
</tr>
<tr class="even">
<td align="center">precipitation</td>
<td align="center">Average precipitation (inches)</td>
</tr>
<tr class="odd">
<td align="center">marijuana</td>
<td align="center">The proportion of people using marijuana (%)</td>
</tr>
<tr class="even">
<td align="center">education</td>
<td align="center">Educational attainment - bachelor’s degree or higher (%)</td>
</tr>
<tr class="odd">
<td align="center">gdp</td>
<td align="center">GDP per capita (dollars)</td>
</tr>
<tr class="even">
<td align="center">gender</td>
<td align="center">Male (%)</td>
</tr>
</tbody>
</table>
<pre class="r"><code>regression_data = read_csv(&quot;./data/us_2017.csv&quot;) %&gt;%
  janitor::clean_names() %&gt;% 
  filter(state != &quot;District of Columbia&quot;) %&gt;% 
  mutate(
    suicide = suicide_rate,
    gun = guns_number_per_capita_average,
    alcohol = alcohol_consumption,
    marijuana = marijuana_usage * 100,
    education = (advanced_degree + bachelors_degree) * 100,
    gender = male_proportion * 100
    ) %&gt;% 
  select(state, suicide, gun, alcohol, temperature, precipitation, marijuana, education, gdp, gender) %&gt;% 
  # replace missing value with mean value
  mutate(
    gun = replace_na(gun, mean(gun, na.rm = TRUE)),
    temperature = replace_na(temperature, mean(temperature, na.rm = TRUE)))</code></pre>
<div id="simple-linear-regression" class="section level2">
<h2>Simple linear regression</h2>
<p>First, we used scatter plot to see the relationship between suicide rate and each covariate. The scatter plots with linear regression line are shown below:</p>
<pre class="r"><code>fit_gun = lm(suicide ~ gun, data = regression_data)
fit_alcohol = lm(suicide ~ alcohol, data = regression_data)
fit_education = lm(suicide ~ education, data = regression_data)
fit_gdp = lm(suicide ~ gdp, data = regression_data)
fit_gender = lm(suicide ~ gender, data = regression_data)
fit_marijuana = lm(suicide ~ marijuana, data = regression_data)
fit_precipitation = lm(suicide ~ precipitation, data = regression_data)
fit_temperature = lm(suicide ~ temperature, data = regression_data)

gun_ly =
  regression_data %&gt;% 
  plot_ly(
    x = ~gun, y = ~suicide, type = &quot;scatter&quot;, mode = &quot;markers&quot;, color = I(&quot;palegreen4&quot;), text = ~state, name = &quot;gun&quot;) %&gt;%
  add_lines(x = ~gun, y = fitted(fit_gun), line = list(color = I(&quot;palegreen4&quot;), width = 2), name = &quot;lm-gun&quot;)

alcohol_ly =
  regression_data %&gt;% 
  plot_ly(
    x = ~alcohol, y = ~suicide, type = &quot;scatter&quot;, mode = &quot;markers&quot;, color = I(&quot;indianred1&quot;), text = ~state, name = &quot;alcohol&quot;) %&gt;%
  add_lines(x = ~alcohol, y = fitted(fit_alcohol),line = list(color = I(&quot;indianred1&quot;), width = 2), name = &quot;lm-alcohol&quot;)

temp_ly =
  regression_data %&gt;% 
  plot_ly(
    x = ~temperature, y = ~suicide, type = &quot;scatter&quot;, mode = &quot;markers&quot;, color = I(&quot;brown&quot;), text = ~state, name = &quot;temperature&quot;) %&gt;%
  add_lines(x = ~temperature, y = fitted(fit_temperature), line = list(color = I(&quot;brown&quot;), width = 2), name = &quot;lm-temperature&quot;)

precip_ly =
  regression_data %&gt;% 
  plot_ly(
    x = ~precipitation, y = ~suicide, type = &quot;scatter&quot;, mode = &quot;markers&quot;, color = I(&quot;orange&quot;), text = ~state, name = &quot;precipitation&quot;) %&gt;%
  add_lines(x = ~precipitation, y = fitted(fit_precipitation), line = list(color = I(&quot;orange&quot;), width = 2), name = &quot;lm-precipitation&quot;)

mari_ly =
  regression_data %&gt;% 
  plot_ly(
    x = ~marijuana, y = ~suicide, type = &quot;scatter&quot;, mode = &quot;markers&quot;,color = I(&quot;snow4&quot;), text = ~state, name = &quot;marijuana&quot;) %&gt;%
  add_lines(x = ~marijuana, y = fitted(fit_marijuana), line = list(color = I(&quot;snow4&quot;), width = 2), name = &quot;lm-marijuana&quot;)

edu_ly =
  regression_data %&gt;% 
  plot_ly(
    x = ~education, y = ~suicide, type = &quot;scatter&quot;, mode = &quot;markers&quot;, color = I(&quot;plum&quot;), text = ~state, name = &quot;education&quot;) %&gt;%
  add_lines(x = ~education, y = fitted(fit_education), line = list(color = I(&quot;plum&quot;), width = 2), name = &quot;lm-education&quot;)

gdp_ly =
  regression_data %&gt;% 
  plot_ly(
    x = ~gdp, y = ~suicide, type = &quot;scatter&quot;, mode = &quot;markers&quot;, color = I(&quot;royalblue1&quot;), text = ~state, name = &quot;gdp&quot;) %&gt;%
  add_lines(x = ~gdp, y = fitted(fit_gdp), line = list(color = I(&quot;royalblue1&quot;), width = 2), name = &quot;lm-gdp&quot;)

gender_ly =
  regression_data %&gt;% 
  plot_ly(
    x = ~gender, y = ~suicide, type = &quot;scatter&quot;, mode = &quot;markers&quot;, color = I(&quot;purple1&quot;), text = ~state, name = &quot;gender&quot;) %&gt;%
  add_lines(x = ~gender, y = fitted(fit_gender), line = list(color =  I(&quot;purple1&quot;), width = 2), name = &quot;lm-gender&quot;)

subplot(gun_ly, alcohol_ly, temp_ly, precip_ly, mari_ly, edu_ly, gdp_ly, gender_ly, nrows = 4, shareX = FALSE, shareY = TRUE)</code></pre>
<div id="htmlwidget-25860261f04b4c22b553" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-25860261f04b4c22b553">{"x":{"data":[{"x":[33.15,21.38,25.61,26.57,8.71,16.48,22.96,5.04,16.35,18.22,5.5,28.86,11.44,17.1,9.05,18.06,18.2,24.94,11.5,17.03,5.41,6.59,14.22,11.89,11.94,21.06,11.57,25.64,46.76,6.38,46.73,3.83,14.818,17.56,14.87,18.13,14.816,18.45,3.98,21.01,24.29,14.76,20.79,23.48,9.41,36.34,12.4,19.42,11.19,17.6302857142857],"y":[17.1290940842673,27.0345163187099,18.8846780411814,21.0033755187185,10.8759838623669,21.0088754473303,11.2870465951579,11.6431499294654,15.3399668325041,13.9030329610229,15.9015031473768,22.8312762858173,11.4981827481485,16.3796281824403,15.1952928924494,18.9487364591196,17.1972945018723,15.3703846417409,20.5104097815192,10.4094774491889,9.9419532789422,14.6150827855103,13.9511380219438,14.8453470057974,18.827087189533,29.605147297507,14.3223497403228,20.9136705693288,19.734955819764,8.8277973235451,23.5145373478858,8.54433930216225,14.8051977632763,20.3867390881303,14.9074387862223,19.2324130267544,19.8900447429453,15.844708425738,12.1739573571754,16.6787112968813,21.9624545515175,17.3466762279362,13.3158586683237,21.3744582638717,17.7982448685736,13.8842647360927,17.4729260791253,21.5876029885613,15.9607059497888,27.100972700517],"mode":"markers","text":["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"],"name":"gun","type":"scatter","marker":{"color":"rgba(84,139,84,1)","line":{"color":"rgba(84,139,84,1)"}},"textfont":{"color":"rgba(84,139,84,1)"},"error_y":{"color":"rgba(84,139,84,1)"},"error_x":{"color":"rgba(84,139,84,1)"},"line":{"color":"rgba(84,139,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[3.83,3.98,5.04,5.41,5.5,6.38,6.59,8.71,9.05,9.41,11.19,11.44,11.5,11.57,11.89,11.94,12.4,14.22,14.76,14.816,14.818,14.87,16.35,16.48,17.03,17.1,17.56,17.6302857142857,18.06,18.13,18.2,18.22,18.45,19.42,20.79,21.01,21.06,21.38,22.96,23.48,24.29,24.94,25.61,25.64,26.57,28.86,33.15,36.34,46.73,46.76],"y":[13.8124507558292,13.8474709327504,14.0949468496605,14.1813299527328,14.2023420588856,14.4077937634901,14.4568220111799,14.9517738449999,15.0311529126881,15.115201337299,15.530774103431,15.5891410649664,15.6031491357349,15.6194918849648,15.6942015957301,15.7058749880371,15.8132701972622,16.2381816772399,16.3642543141563,16.3773285135402,16.3777954492325,16.3899357772319,16.7354681895214,16.7658190095198,16.8942263248976,16.9105690741275,17.0179642833526,17.0343737376814,17.1346982064234,17.1510409556533,17.1673837048832,17.172053061806,17.2257506664186,17.4522144771759,17.7720654263898,17.823428352541,17.835101744848,17.9098114556133,18.278690652517,18.4000939325106,18.5892028878852,18.7409569878772,18.8973804447921,18.9043844801763,19.121509577088,19.6561509447521,20.6577280046994,21.4024904338909,23.8282213553015,23.8352253906858],"mode":"lines","text":["New York","Rhode Island","Delaware","Massachusetts","Hawaii","New Jersey","Michigan","California","Iowa","Vermont","Wisconsin","Illinois","Maine","Nebraska","Mississippi","Missouri","Washington","Minnesota","Tennessee","Oregon","North Carolina","Ohio","Florida","Colorado","Maryland","Indiana","North Dakota","Wyoming","Kansas","Oklahoma","Kentucky","Georgia","Pennsylvania","West Virginia","Texas","South Carolina","Montana","Alaska","Connecticut","Utah","South Dakota","Louisiana","Arizona","Nevada","Arkansas","Idaho","Alabama","Virginia","New Mexico","New Hampshire"],"name":"lm-gun","type":"scatter","line":{"color":["palegreen4"],"width":2},"marker":{"color":"rgba(84,139,84,1)","line":{"color":"rgba(84,139,84,1)"}},"textfont":{"color":"rgba(84,139,84,1)"},"error_y":{"color":"rgba(84,139,84,1)"},"error_x":{"color":"rgba(84,139,84,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[1.99,2.81,2.3,1.82,2.3,2.85,2.4,3.6,2.63,1.92,2.65,2.92,2.38,2.11,2.4,1.97,1.97,2.56,2.84,2.13,2.58,2.34,2.77,2.2,2.53,3.11,2.2,3.43,4.74,2.33,2.16,2.2,2.13,3.15,2.02,1.87,2.76,2.34,2.59,2.19,2.86,2.11,2.34,1.36,3.1,2.12,2.24,1.74,2.99,2.68],"y":[17.1290940842673,27.0345163187099,18.8846780411814,21.0033755187185,10.8759838623669,21.0088754473303,11.2870465951579,11.6431499294654,15.3399668325041,13.9030329610229,15.9015031473768,22.8312762858173,11.4981827481485,16.3796281824403,15.1952928924494,18.9487364591196,17.1972945018723,15.3703846417409,20.5104097815192,10.4094774491889,9.9419532789422,14.6150827855103,13.9511380219438,14.8453470057974,18.827087189533,29.605147297507,14.3223497403228,20.9136705693288,19.734955819764,8.8277973235451,23.5145373478858,8.54433930216225,14.8051977632763,20.3867390881303,14.9074387862223,19.2324130267544,19.8900447429453,15.844708425738,12.1739573571754,16.6787112968813,21.9624545515175,17.3466762279362,13.3158586683237,21.3744582638717,17.7982448685736,13.8842647360927,17.4729260791253,21.5876029885613,15.9607059497888,27.100972700517],"mode":"markers","text":["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"],"name":"alcohol","type":"scatter","marker":{"color":"rgba(255,106,106,1)","line":{"color":"rgba(255,106,106,1)"}},"textfont":{"color":"rgba(255,106,106,1)"},"error_y":{"color":"rgba(255,106,106,1)"},"error_x":{"color":"rgba(255,106,106,1)"},"line":{"color":"rgba(255,106,106,1)"},"xaxis":"x2","yaxis":"y","frame":null},{"x":[1.36,1.74,1.82,1.87,1.92,1.97,1.97,1.99,2.02,2.11,2.11,2.12,2.13,2.13,2.16,2.19,2.2,2.2,2.2,2.24,2.3,2.3,2.33,2.34,2.34,2.34,2.38,2.4,2.4,2.53,2.56,2.58,2.59,2.63,2.65,2.68,2.76,2.77,2.81,2.84,2.85,2.86,2.92,2.99,3.1,3.11,3.15,3.43,3.6,4.74],"y":[15.2342816753523,15.8479861286854,15.9771870662292,16.0579376521941,16.138688238159,16.2194388241239,16.2194388241239,16.2517390585098,16.3001894100888,16.4455404648255,16.4455404648255,16.4616905820185,16.4778406992115,16.4778406992115,16.5262910507904,16.5747414023693,16.5908915195623,16.5908915195623,16.5908915195623,16.6554919883342,16.7523926914921,16.7523926914921,16.800843043071,16.816993160264,16.816993160264,16.816993160264,16.8815936290359,16.9138938634218,16.9138938634218,17.1238453869305,17.1722957385094,17.2045959728954,17.2207460900884,17.2853465588603,17.3176467932462,17.3660971448252,17.495298082369,17.5114481995619,17.5760486683338,17.6244990199128,17.6406491371057,17.6567992542987,17.7536999574566,17.8667507778074,18.0444020669301,18.0605521841231,18.125152652895,18.5773559342983,18.8519079265789,20.6930212865782],"mode":"lines","text":["Utah","West Virginia","Arkansas","Oklahoma","Georgia","Kansas","Kentucky","Alabama","Ohio","Indiana","Tennessee","Virginia","Maryland","North Carolina","New Mexico","South Carolina","Mississippi","Nebraska","New York","Washington","Arizona","California","New Jersey","Michigan","Pennsylvania","Texas","Illinois","Connecticut","Iowa","Missouri","Louisiana","Massachusetts","Rhode Island","Florida","Hawaii","Wyoming","Oregon","Minnesota","Alaska","Maine","Colorado","South Dakota","Idaho","Wisconsin","Vermont","Montana","North Dakota","Nevada","Delaware","New Hampshire"],"name":"lm-alcohol","type":"scatter","line":{"color":["indianred1"],"width":2},"marker":{"color":"rgba(255,106,106,1)","line":{"color":"rgba(255,106,106,1)"}},"textfont":{"color":"rgba(255,106,106,1)"},"error_y":{"color":"rgba(255,106,106,1)"},"error_x":{"color":"rgba(255,106,106,1)"},"xaxis":"x2","yaxis":"y","frame":null},{"x":[62.3669565217391,37.716,63.3745454545455,60.8084210526316,59.4571428571429,45.9685714285714,48.6883333333333,55.785,71.2053333333333,63.47,71.9725,46.567,51.5903703703704,51.4277777777778,47.89,55.1283333333333,56.2394736842105,66.5979166666667,43.928,56.5916666666667,47.215,46.656,44.0489473684211,63.6773913043478,54.8614285714286,44.0525,49.7445454545455,50.84375,44.694,54.1625,53.8731578947368,46.1746153846154,58.8046153846154,41.538,50.4513157894737,59.8633333333333,51.0388235294118,48.9024242424242,53.0177816419875,61.6395238095238,45.9336363636364,57.8212,65.4070588235294,48.5822222222222,44.7975,54.194,50.4331578947368,52.9733333333333,45.2327272727273,43.48125],"y":[17.1290940842673,27.0345163187099,18.8846780411814,21.0033755187185,10.8759838623669,21.0088754473303,11.2870465951579,11.6431499294654,15.3399668325041,13.9030329610229,15.9015031473768,22.8312762858173,11.4981827481485,16.3796281824403,15.1952928924494,18.9487364591196,17.1972945018723,15.3703846417409,20.5104097815192,10.4094774491889,9.9419532789422,14.6150827855103,13.9511380219438,14.8453470057974,18.827087189533,29.605147297507,14.3223497403228,20.9136705693288,19.734955819764,8.8277973235451,23.5145373478858,8.54433930216225,14.8051977632763,20.3867390881303,14.9074387862223,19.2324130267544,19.8900447429453,15.844708425738,12.1739573571754,16.6787112968813,21.9624545515175,17.3466762279362,13.3158586683237,21.3744582638717,17.7982448685736,13.8842647360927,17.4729260791253,21.5876029885613,15.9607059497888,27.100972700517],"mode":"markers","text":["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"],"name":"temperature","type":"scatter","marker":{"color":"rgba(165,42,42,1)","line":{"color":"rgba(165,42,42,1)"}},"textfont":{"color":"rgba(165,42,42,1)"},"error_y":{"color":"rgba(165,42,42,1)"},"error_x":{"color":"rgba(165,42,42,1)"},"line":{"color":"rgba(165,42,42,1)"},"xaxis":"x3","yaxis":"y2","frame":null},{"x":[37.716,41.538,43.48125,43.928,44.0489473684211,44.0525,44.694,44.7975,45.2327272727273,45.9336363636364,45.9685714285714,46.1746153846154,46.567,46.656,47.215,47.89,48.5822222222222,48.6883333333333,48.9024242424242,49.7445454545455,50.4331578947368,50.4513157894737,50.84375,51.0388235294118,51.4277777777778,51.5903703703704,52.9733333333333,53.0177816419875,53.8731578947368,54.1625,54.194,54.8614285714286,55.1283333333333,55.785,56.2394736842105,56.5916666666667,57.8212,58.8046153846154,59.4571428571429,59.8633333333333,60.8084210526316,61.6395238095238,62.3669565217391,63.3745454545455,63.47,63.6773913043478,65.4070588235294,66.5979166666667,71.2053333333333,71.9725],"y":[19.9766692537659,19.2417578737984,18.8681010085127,18.7821979056868,18.7589416007602,18.7582584847538,18.6349079744845,18.6150065281667,18.5313190672564,18.3965451093203,18.3898276376351,18.3502085774388,18.2747590957092,18.257645774721,18.1501587361543,18.0203666949512,17.8872630872648,17.8668595647382,17.8256932001546,17.6637663393226,17.5313568367889,17.5278653549788,17.4524063368719,17.4148967197356,17.3401068444318,17.3088428081695,17.0429204587307,17.0343737376814,16.869898137917,16.8142621342902,16.8082051723674,16.679868999563,16.6285473494083,16.5022805241392,16.4148922765143,16.3471710230471,16.1107508140685,15.9216552731504,15.7961843507795,15.718080215932,15.5363544911859,15.3765463085688,15.2366722692261,15.0429285295483,15.0245740994792,14.9846959650805,14.6521077014995,14.4231241900277,13.5371893547097,13.3896750915843],"mode":"lines","text":["Alaska","North Dakota","Wyoming","Maine","Minnesota","Montana","New Hampshire","Vermont","Wisconsin","South Dakota","Colorado","New York","Idaho","Michigan","Massachusetts","Iowa","Utah","Connecticut","Pennsylvania","Nebraska","Washington","Ohio","Nevada","Oregon","Indiana","Illinois","West Virginia","Rhode Island","New Mexico","New Jersey","Virginia","Missouri","Kansas","Delaware","Kentucky","Maryland","Tennessee","North Carolina","California","Oklahoma","Arkansas","South Carolina","Alabama","Arizona","Georgia","Mississippi","Texas","Louisiana","Florida","Hawaii"],"name":"lm-temperature","type":"scatter","line":{"color":["brown"],"width":2},"marker":{"color":"rgba(165,42,42,1)","line":{"color":"rgba(165,42,42,1)"}},"textfont":{"color":"rgba(165,42,42,1)"},"error_y":{"color":"rgba(165,42,42,1)"},"error_x":{"color":"rgba(165,42,42,1)"},"xaxis":"x3","yaxis":"y2","frame":null},{"x":[56,55,13,49,22,15,47,45,54,50,110,19,38,40,32,27,47,57,41,43,45,32,26,56,40,15,22,22,42,45,13,39,50,17,38,33,28,41,44,48,18,52,27,12,39,43,38,44,31,13],"y":[17.1290940842673,27.0345163187099,18.8846780411814,21.0033755187185,10.8759838623669,21.0088754473303,11.2870465951579,11.6431499294654,15.3399668325041,13.9030329610229,15.9015031473768,22.8312762858173,11.4981827481485,16.3796281824403,15.1952928924494,18.9487364591196,17.1972945018723,15.3703846417409,20.5104097815192,10.4094774491889,9.9419532789422,14.6150827855103,13.9511380219438,14.8453470057974,18.827087189533,29.605147297507,14.3223497403228,20.9136705693288,19.734955819764,8.8277973235451,23.5145373478858,8.54433930216225,14.8051977632763,20.3867390881303,14.9074387862223,19.2324130267544,19.8900447429453,15.844708425738,12.1739573571754,16.6787112968813,21.9624545515175,17.3466762279362,13.3158586683237,21.3744582638717,17.7982448685736,13.8842647360927,17.4729260791253,21.5876029885613,15.9607059497888,27.100972700517],"mode":"markers","text":["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"],"name":"precipitation","type":"scatter","marker":{"color":"rgba(255,165,0,1)","line":{"color":"rgba(255,165,0,1)"}},"textfont":{"color":"rgba(255,165,0,1)"},"error_y":{"color":"rgba(255,165,0,1)"},"error_x":{"color":"rgba(255,165,0,1)"},"line":{"color":"rgba(255,165,0,1)"},"xaxis":"x4","yaxis":"y2","frame":null},{"x":[12,13,13,13,15,15,17,18,19,22,22,22,26,27,27,28,31,32,32,33,38,38,38,39,39,40,40,41,41,42,43,43,44,44,45,45,45,47,47,48,49,50,50,52,54,55,56,56,57,110],"y":[19.4941273490151,19.3975148741002,19.3975148741002,19.3975148741002,19.2042899242704,19.2042899242704,19.0110649744406,18.9144524995256,18.8178400246107,18.528002599866,18.528002599866,18.528002599866,18.1415527002063,18.0449402252914,18.0449402252914,17.9483277503765,17.6584903256318,17.5618778507169,17.5618778507169,17.4652653758019,16.9822030012274,16.9822030012274,16.9822030012274,16.8855905263125,16.8855905263125,16.7889780513976,16.7889780513976,16.6923655764826,16.6923655764826,16.5957531015677,16.4991406266528,16.4991406266528,16.4025281517379,16.4025281517379,16.305915676823,16.305915676823,16.305915676823,16.1126907269932,16.1126907269932,16.0160782520782,15.9194657771633,15.8228533022484,15.8228533022484,15.6296283524186,15.4364034025888,15.3397909276739,15.2431784527589,15.2431784527589,15.146565977844,10.0261048073536],"mode":"lines","text":["Utah","Arizona","New Mexico","Wyoming","Colorado","Montana","North Dakota","South Dakota","Idaho","California","Nebraska","Nevada","Minnesota","Kansas","Texas","Oregon","Wisconsin","Iowa","Michigan","Oklahoma","Illinois","Ohio","Washington","New York","Vermont","Indiana","Missouri","Maine","Pennsylvania","New Hampshire","Maryland","Virginia","Rhode Island","West Virginia","Delaware","Massachusetts","New Jersey","Connecticut","Kentucky","South Carolina","Arkansas","Georgia","North Carolina","Tennessee","Florida","Alaska","Alabama","Mississippi","Louisiana","Hawaii"],"name":"lm-precipitation","type":"scatter","line":{"color":["orange"],"width":2},"marker":{"color":"rgba(255,165,0,1)","line":{"color":"rgba(255,165,0,1)"}},"textfont":{"color":"rgba(255,165,0,1)"},"error_y":{"color":"rgba(255,165,0,1)"},"error_x":{"color":"rgba(255,165,0,1)"},"xaxis":"x4","yaxis":"y2","frame":null},{"x":[10.63,23.43,14.14,12.78,17.81,25.65,16.37,14.92,13.71,11.78,13.29,12.7,13.88,14.54,11.51,11.95,12.95,12.48,22.46,15.65,20.28,16.94,13.78,11.48,13.95,19.86,11.46,17.06,18.9,12.21,17.71,14.74,12.23,11.02,13.92,12.18,27.38,13.47,21.24,11.14,12.33,13.55,10.67,10.58,24.34,11.92,23.21,13.1,12.71,12.19],"y":[17.1290940842673,27.0345163187099,18.8846780411814,21.0033755187185,10.8759838623669,21.0088754473303,11.2870465951579,11.6431499294654,15.3399668325041,13.9030329610229,15.9015031473768,22.8312762858173,11.4981827481485,16.3796281824403,15.1952928924494,18.9487364591196,17.1972945018723,15.3703846417409,20.5104097815192,10.4094774491889,9.9419532789422,14.6150827855103,13.9511380219438,14.8453470057974,18.827087189533,29.605147297507,14.3223497403228,20.9136705693288,19.734955819764,8.8277973235451,23.5145373478858,8.54433930216225,14.8051977632763,20.3867390881303,14.9074387862223,19.2324130267544,19.8900447429453,15.844708425738,12.1739573571754,16.6787112968813,21.9624545515175,17.3466762279362,13.3158586683237,21.3744582638717,17.7982448685736,13.8842647360927,17.4729260791253,21.5876029885613,15.9607059497888,27.100972700517],"mode":"markers","text":["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"],"name":"marijuana","type":"scatter","marker":{"color":"rgba(139,137,137,1)","line":{"color":"rgba(139,137,137,1)"}},"textfont":{"color":"rgba(139,137,137,1)"},"error_y":{"color":"rgba(139,137,137,1)"},"error_x":{"color":"rgba(139,137,137,1)"},"line":{"color":"rgba(139,137,137,1)"},"xaxis":"x5","yaxis":"y3","frame":null},{"x":[10.58,10.63,10.67,11.02,11.14,11.46,11.48,11.51,11.78,11.92,11.95,12.18,12.19,12.21,12.23,12.33,12.48,12.7,12.71,12.78,12.95,13.1,13.29,13.47,13.55,13.71,13.78,13.88,13.92,13.95,14.14,14.54,14.74,14.92,15.65,16.37,16.94,17.06,17.71,17.81,18.9,19.86,20.28,21.24,22.46,23.21,23.43,24.34,25.65,27.38],"y":[16.0817900028389,16.0921812208209,16.1004941952064,16.1732327210802,16.1981716442369,16.2646754393215,16.2688319265143,16.2750666573034,16.331179234406,16.3602746447555,16.3665093755447,16.4143089782617,16.4163872218581,16.4205437090509,16.4247001962437,16.4454826322076,16.4766562861535,16.5223776452741,16.5244558888705,16.5390035940453,16.574333735184,16.6055073891299,16.6449940174613,16.6824024021964,16.6990283509675,16.7322802485098,16.7468279536846,16.7676103896485,16.775923364034,16.7821580948232,16.8216447231547,16.9047744670104,16.9463393389382,16.9837477236733,17.13545950621,17.2850930451502,17.4035529301446,17.4284918533013,17.5635776870668,17.5843601230308,17.8108886750376,18.0104000602913,18.0976862913397,18.2971976765934,18.5507433953533,18.7066116650828,18.7523330242034,18.9414531914751,19.2137031026026,19.5732392447785],"mode":"lines","text":["Utah","Alabama","Texas","North Dakota","South Carolina","Nebraska","Mississippi","Iowa","Georgia","Virginia","Kansas","Oklahoma","Wyoming","New Jersey","North Carolina","South Dakota","Louisiana","Idaho","Wisconsin","Arkansas","Kentucky","West Virginia","Hawaii","Pennsylvania","Tennessee","Florida","Minnesota","Illinois","Ohio","Missouri","Arizona","Indiana","New York","Delaware","Maryland","Connecticut","Michigan","Nevada","New Mexico","California","New Hampshire","Montana","Massachusetts","Rhode Island","Maine","Washington","Alaska","Vermont","Colorado","Oregon"],"name":"lm-marijuana","type":"scatter","line":{"color":["snow4"],"width":2},"marker":{"color":"rgba(139,137,137,1)","line":{"color":"rgba(139,137,137,1)"}},"textfont":{"color":"rgba(139,137,137,1)"},"error_y":{"color":"rgba(139,137,137,1)"},"error_x":{"color":"rgba(139,137,137,1)"},"xaxis":"x5","yaxis":"y3","frame":null},{"x":[24.5244743314563,28.9879732964273,28.4456868921156,22.0281301459887,32.5759712083064,39.4297960706855,38.4308411452338,30.9680142431777,28.4512310515942,29.9310289810342,32.0373455786736,26.7659363961578,33.4474679956183,25.3191533673224,27.6812768809535,32.3492201632339,23.1922922752302,23.3970199241996,30.2810570542074,38.9946396309835,42.0874503031529,28.0810842664225,34.7631066307432,21.3341744623616,28.186587561756,30.7291037747241,30.5915992485261,23.6847333593154,36.0370889575091,38.091347419788,26.8736202890788,35.2893668303246,29.8599891981896,28.8924591649674,27.2386681287754,24.8430382284937,32.2709852524328,30.0836500035505,32.9643296432964,27.0050736693909,27.8474148464605,26.0530540700466,28.7055762516693,32.5371036492665,36.7988125142727,37.5565086744479,34.4634200391948,19.8985827088157,29.0310751580934,26.7497304544063],"y":[17.1290940842673,27.0345163187099,18.8846780411814,21.0033755187185,10.8759838623669,21.0088754473303,11.2870465951579,11.6431499294654,15.3399668325041,13.9030329610229,15.9015031473768,22.8312762858173,11.4981827481485,16.3796281824403,15.1952928924494,18.9487364591196,17.1972945018723,15.3703846417409,20.5104097815192,10.4094774491889,9.9419532789422,14.6150827855103,13.9511380219438,14.8453470057974,18.827087189533,29.605147297507,14.3223497403228,20.9136705693288,19.734955819764,8.8277973235451,23.5145373478858,8.54433930216225,14.8051977632763,20.3867390881303,14.9074387862223,19.2324130267544,19.8900447429453,15.844708425738,12.1739573571754,16.6787112968813,21.9624545515175,17.3466762279362,13.3158586683237,21.3744582638717,17.7982448685736,13.8842647360927,17.4729260791253,21.5876029885613,15.9607059497888,27.100972700517],"mode":"markers","text":["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"],"name":"education","type":"scatter","marker":{"color":"rgba(221,160,221,1)","line":{"color":"rgba(221,160,221,1)"}},"textfont":{"color":"rgba(221,160,221,1)"},"error_y":{"color":"rgba(221,160,221,1)"},"error_x":{"color":"rgba(221,160,221,1)"},"line":{"color":"rgba(221,160,221,1)"},"xaxis":"x6","yaxis":"y3","frame":null},{"x":[19.8985827088157,21.3341744623616,22.0281301459887,23.1922922752302,23.3970199241996,23.6847333593154,24.5244743314563,24.8430382284937,25.3191533673224,26.0530540700466,26.7497304544063,26.7659363961578,26.8736202890788,27.0050736693909,27.2386681287754,27.6812768809535,27.8474148464605,28.0810842664225,28.186587561756,28.4456868921156,28.4512310515942,28.7055762516693,28.8924591649674,28.9879732964273,29.0310751580934,29.8599891981896,29.9310289810342,30.0836500035505,30.2810570542074,30.5915992485261,30.7291037747241,30.9680142431777,32.0373455786736,32.2709852524328,32.3492201632339,32.5371036492665,32.5759712083064,32.9643296432964,33.4474679956183,34.4634200391948,34.7631066307432,35.2893668303246,36.0370889575091,36.7988125142727,37.5565086744479,38.091347419788,38.4308411452338,38.9946396309835,39.4297960706855,42.0874503031529],"y":[20.8707410271533,20.3317012584641,20.0711329525659,19.6340102933468,19.5571386170697,19.4491072194732,19.1337990698801,19.0141838596731,18.8354108946782,18.5598439279134,18.2982540461459,18.2921689964989,18.2517355650667,18.2023771039709,18.11466644177,17.9484745429906,17.88609262259,17.7983538139942,17.7587391590813,17.6614518608229,17.6593701252351,17.5638679203241,17.4936966323466,17.4578327349666,17.4416487345465,17.1304059098834,17.103731705314,17.0464251622309,16.9723022434687,16.8556990433038,16.8040684820301,16.7143617507574,16.3128464074754,16.2251187680622,16.1957429179171,16.1251959322567,16.1106018389272,15.9647799919791,15.7833699323036,15.4018975859934,15.289370476118,15.0917689117791,14.8110122401935,14.5249982749915,14.2404965272567,14.039673867986,13.9121998707415,13.7005033319482,13.5371096470645,12.5392066435215],"mode":"lines","text":["West Virginia","Mississippi","Arkansas","Kentucky","Louisiana","Nevada","Alabama","Oklahoma","Indiana","Tennessee","Wyoming","Idaho","New Mexico","South Carolina","Ohio","Iowa","South Dakota","Michigan","Missouri","Arizona","Florida","Texas","North Dakota","Alaska","Wisconsin","North Carolina","Georgia","Pennsylvania","Maine","Nebraska","Montana","Delaware","Hawaii","Oregon","Kansas","Utah","California","Rhode Island","Illinois","Washington","Minnesota","New York","New Hampshire","Vermont","Virginia","New Jersey","Connecticut","Maryland","Colorado","Massachusetts"],"name":"lm-education","type":"scatter","line":{"color":["plum"],"width":2},"marker":{"color":"rgba(221,160,221,1)","line":{"color":"rgba(221,160,221,1)"}},"textfont":{"color":"rgba(221,160,221,1)"},"error_y":{"color":"rgba(221,160,221,1)"},"error_x":{"color":"rgba(221,160,221,1)"},"xaxis":"x6","yaxis":"y3","frame":null},{"x":[36856,67705,38414,36196,57328,52622,63747,64040,39093,43913,50320,35467,53432,44797,50086,46890,38603,44293,38450,54894,64507,42631,53380,31633,42943,39686,52878,43649,50456,56472,41577,64093,44096,67305,46826,45864,49792,50418,47118,36796,47706,42797,54421,44204,43495,51716,55780,36453,46859,60908],"y":[17.1290940842673,27.0345163187099,18.8846780411814,21.0033755187185,10.8759838623669,21.0088754473303,11.2870465951579,11.6431499294654,15.3399668325041,13.9030329610229,15.9015031473768,22.8312762858173,11.4981827481485,16.3796281824403,15.1952928924494,18.9487364591196,17.1972945018723,15.3703846417409,20.5104097815192,10.4094774491889,9.9419532789422,14.6150827855103,13.9511380219438,14.8453470057974,18.827087189533,29.605147297507,14.3223497403228,20.9136705693288,19.734955819764,8.8277973235451,23.5145373478858,8.54433930216225,14.8051977632763,20.3867390881303,14.9074387862223,19.2324130267544,19.8900447429453,15.844708425738,12.1739573571754,16.6787112968813,21.9624545515175,17.3466762279362,13.3158586683237,21.3744582638717,17.7982448685736,13.8842647360927,17.4729260791253,21.5876029885613,15.9607059497888,27.100972700517],"mode":"markers","text":["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"],"name":"gdp","type":"scatter","marker":{"color":"rgba(72,118,255,1)","line":{"color":"rgba(72,118,255,1)"}},"textfont":{"color":"rgba(72,118,255,1)"},"error_y":{"color":"rgba(72,118,255,1)"},"error_x":{"color":"rgba(72,118,255,1)"},"line":{"color":"rgba(72,118,255,1)"},"xaxis":"x7","yaxis":"y4","frame":null},{"x":[31633,35467,36196,36453,36796,36856,38414,38450,38603,39093,39686,41577,42631,42797,42943,43495,43649,43913,44096,44204,44293,44797,45864,46826,46859,46890,47118,47706,49792,50086,50320,50418,50456,51716,52622,52878,53380,53432,54421,54894,55780,56472,57328,60908,63747,64040,64093,64507,67305,67705],"y":[19.5375009922568,18.960727615449,18.8510594381687,18.8123972686748,18.7607975638639,18.7517713764334,18.5173913761552,18.5119756636969,18.4889588857492,18.4152450217336,18.326036202629,18.0415608621117,17.8830008362496,17.8580283843586,17.8360646616111,17.7530237372506,17.7298565228457,17.6901412981516,17.6626114264886,17.6463642891138,17.6329754444252,17.5571554700092,17.3966397702038,17.2519198984017,17.246955495315,17.2422919651426,17.2079924529067,17.119535816088,16.8057253664216,16.7614970480123,16.7262949170334,16.7115521442303,16.7058355588576,16.5162856228175,16.3799901926173,16.3414784595805,16.2659593580788,16.2581366623058,16.10935500616,16.0381985619164,15.9049118608596,15.8008098324947,15.6720362251532,15.1334737084678,14.7063846065488,14.6623067245967,14.6543335923664,14.5920528990961,14.1711316919213,14.1109571090514],"mode":"lines","text":["Mississippi","Idaho","Arkansas","West Virginia","South Carolina","Alabama","Arizona","Maine","Kentucky","Florida","Montana","New Mexico","Michigan","Tennessee","Missouri","Vermont","Nevada","Georgia","North Carolina","Utah","Louisiana","Indiana","Oklahoma","Ohio","Wisconsin","Kansas","Rhode Island","South Dakota","Oregon","Iowa","Hawaii","Pennsylvania","New Hampshire","Virginia","Colorado","Nebraska","Minnesota","Illinois","Texas","Maryland","Washington","New Jersey","California","Wyoming","Connecticut","Delaware","New York","Massachusetts","North Dakota","Alaska"],"name":"lm-gdp","type":"scatter","line":{"color":["royalblue1"],"width":2},"marker":{"color":"rgba(72,118,255,1)","line":{"color":"rgba(72,118,255,1)"}},"textfont":{"color":"rgba(72,118,255,1)"},"error_y":{"color":"rgba(72,118,255,1)"},"error_x":{"color":"rgba(72,118,255,1)"},"xaxis":"x7","yaxis":"y4","frame":null},{"x":[48.409404631666,52.2836731797322,49.7173141854575,49.1320546460565,49.6945277588368,50.3345012460867,48.821353642957,48.3932972880817,48.8783048359734,48.6654766309672,50.1623774638574,50.1156998223004,49.1522160208586,49.305305769559,49.7417912834332,49.8419050620245,49.2641421367616,48.8745356062432,48.9944285043794,48.480968088012,48.5488757064873,49.22303670303,49.7945524571756,48.4527328172648,49.1080442533056,50.3531199160775,49.9006810147098,50.1577531179548,49.5242386216809,48.8202065282616,49.5263089838942,48.5529158842542,48.6832864502071,51.2711926109985,49.0032730319715,49.5453925650951,49.5558775082215,48.9735729161534,48.6006083203808,48.517276497805,50.474549999655,48.7786450950449,49.6802462751986,50.3472624090336,49.4271691009642,49.1938271692393,50.0081220749896,49.4873770346453,49.7411173494944,50.9978163865945],"y":[17.1290940842673,27.0345163187099,18.8846780411814,21.0033755187185,10.8759838623669,21.0088754473303,11.2870465951579,11.6431499294654,15.3399668325041,13.9030329610229,15.9015031473768,22.8312762858173,11.4981827481485,16.3796281824403,15.1952928924494,18.9487364591196,17.1972945018723,15.3703846417409,20.5104097815192,10.4094774491889,9.9419532789422,14.6150827855103,13.9511380219438,14.8453470057974,18.827087189533,29.605147297507,14.3223497403228,20.9136705693288,19.734955819764,8.8277973235451,23.5145373478858,8.54433930216225,14.8051977632763,20.3867390881303,14.9074387862223,19.2324130267544,19.8900447429453,15.844708425738,12.1739573571754,16.6787112968813,21.9624545515175,17.3466762279362,13.3158586683237,21.3744582638717,17.7982448685736,13.8842647360927,17.4729260791253,21.5876029885613,15.9607059497888,27.100972700517],"mode":"markers","text":["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"],"name":"gender","type":"scatter","marker":{"color":"rgba(155,48,255,1)","line":{"color":"rgba(155,48,255,1)"}},"textfont":{"color":"rgba(155,48,255,1)"},"error_y":{"color":"rgba(155,48,255,1)"},"error_x":{"color":"rgba(155,48,255,1)"},"line":{"color":"rgba(155,48,255,1)"},"xaxis":"x8","yaxis":"y4","frame":null},{"x":[48.3932972880817,48.409404631666,48.4527328172648,48.480968088012,48.517276497805,48.5488757064873,48.5529158842542,48.6006083203808,48.6654766309672,48.6832864502071,48.7786450950449,48.8202065282616,48.821353642957,48.8745356062432,48.8783048359734,48.9735729161534,48.9944285043794,49.0032730319715,49.1080442533056,49.1320546460565,49.1522160208586,49.1938271692393,49.22303670303,49.2641421367616,49.305305769559,49.4271691009642,49.4873770346453,49.5242386216809,49.5263089838942,49.5453925650951,49.5558775082215,49.6802462751986,49.6945277588368,49.7173141854575,49.7411173494944,49.7417912834332,49.7945524571756,49.8419050620245,49.9006810147098,50.0081220749896,50.1156998223004,50.1577531179548,50.1623774638574,50.3345012460867,50.3472624090336,50.3531199160775,50.474549999655,50.9978163865945,51.2711926109985,52.2836731797322],"y":[12.809005467205,12.8733977928113,13.0466108754277,13.1594870140665,13.3046371397464,13.4309612926842,13.4471127108813,13.6377727573338,13.8970967951512,13.968295107491,14.3495103510607,14.5156604878811,14.5202463081677,14.7328518367188,14.7479200859804,15.1287732792278,15.2121476618955,15.2475054288394,15.6663493283926,15.7623356727487,15.8429347984907,16.0092836816165,16.1260546315135,16.2903818192442,16.454941669374,16.9421146954045,17.1828079450007,17.3301695072798,17.3384461940633,17.4147366244491,17.4566522803873,17.9538412859173,18.0109343714258,18.102027666523,18.1971855726729,18.199879758303,18.4108030965428,18.6001045995354,18.8350732188681,19.2645903332693,19.6946538813987,19.8627703366297,19.8812570837159,20.5693563082622,20.6203716079167,20.6437881631565,21.1292291943963,23.2210911696603,24.3139672707161,28.3615607246268],"mode":"lines","text":["Delaware","Alabama","Mississippi","Maryland","South Carolina","Massachusetts","New York","Rhode Island","Georgia","North Carolina","Tennessee","New Jersey","Connecticut","Louisiana","Florida","Pennsylvania","Maine","Ohio","Missouri","Arkansas","Illinois","Virginia","Michigan","Kentucky","Indiana","Vermont","West Virginia","New Hampshire","New Mexico","Oklahoma","Oregon","Texas","California","Arizona","Wisconsin","Iowa","Minnesota","Kansas","Nebraska","Washington","Idaho","Nevada","Hawaii","Colorado","Utah","Montana","South Dakota","Wyoming","North Dakota","Alaska"],"name":"lm-gender","type":"scatter","line":{"color":["purple1"],"width":2},"marker":{"color":"rgba(155,48,255,1)","line":{"color":"rgba(155,48,255,1)"}},"textfont":{"color":"rgba(155,48,255,1)"},"error_y":{"color":"rgba(155,48,255,1)"},"error_x":{"color":"rgba(155,48,255,1)"},"xaxis":"x8","yaxis":"y4","frame":null}],"layout":{"xaxis":{"domain":[0,0.48],"automargin":true,"anchor":"y"},"xaxis2":{"domain":[0.52,1],"automargin":true,"anchor":"y"},"xaxis3":{"domain":[0,0.48],"automargin":true,"anchor":"y2"},"xaxis4":{"domain":[0.52,1],"automargin":true,"anchor":"y2"},"xaxis5":{"domain":[0,0.48],"automargin":true,"anchor":"y3"},"xaxis6":{"domain":[0.52,1],"automargin":true,"anchor":"y3"},"xaxis7":{"domain":[0,0.48],"automargin":true,"anchor":"y4"},"xaxis8":{"domain":[0.52,1],"automargin":true,"anchor":"y4"},"yaxis4":{"domain":[0,0.23],"automargin":true,"title":"suicide","anchor":"x7"},"yaxis3":{"domain":[0.27,0.48],"automargin":true,"title":"suicide","anchor":"x5"},"yaxis2":{"domain":[0.52,0.73],"automargin":true,"title":"suicide","anchor":"x3"},"yaxis":{"domain":[0.77,1],"automargin":true,"title":"suicide","anchor":"x"},"annotations":[],"shapes":[],"images":[],"margin":{"b":40,"l":60,"t":25,"r":10},"hovermode":"closest","showlegend":true},"attrs":{"98d36a28de0":{"x":{},"y":{},"mode":"markers","text":{},"name":"gun","color":["palegreen4"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"},"98d36a28de0.1":{"x":{},"y":[20.6577280046994,17.9098114556133,18.8973804447921,19.121509577088,14.9517738449999,16.7658190095198,18.278690652517,14.0949468496605,16.7354681895214,17.172053061806,14.2023420588856,19.6561509447521,15.5891410649664,16.9105690741275,15.0311529126881,17.1346982064234,17.1673837048832,18.7409569878772,15.6031491357349,16.8942263248976,14.1813299527328,14.4568220111799,16.2381816772399,15.6942015957301,15.7058749880371,17.835101744848,15.6194918849648,18.9043844801763,23.8352253906858,14.4077937634901,23.8282213553015,13.8124507558292,16.3777954492325,17.0179642833526,16.3899357772319,17.1510409556533,16.3773285135402,17.2257506664186,13.8474709327504,17.823428352541,18.5892028878852,16.3642543141563,17.7720654263898,18.4000939325106,15.115201337299,21.4024904338909,15.8132701972622,17.4522144771759,15.530774103431,17.0343737376814],"mode":"lines","text":{},"name":"lm-gun","color":["palegreen4"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","line":{"color":["palegreen4"],"width":2},"inherit":true},"98d31a107087":{"x":{},"y":{},"mode":"markers","text":{},"name":"alcohol","color":["indianred1"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"},"98d31a107087.1":{"x":{},"y":[16.2517390585098,17.5760486683338,16.7523926914921,15.9771870662292,16.7523926914921,17.6406491371057,16.9138938634218,18.8519079265789,17.2853465588603,16.138688238159,17.3176467932462,17.7536999574566,16.8815936290359,16.4455404648255,16.9138938634218,16.2194388241239,16.2194388241239,17.1722957385094,17.6244990199128,16.4778406992115,17.2045959728954,16.816993160264,17.5114481995619,16.5908915195623,17.1238453869305,18.0605521841231,16.5908915195623,18.5773559342983,20.6930212865782,16.800843043071,16.5262910507904,16.5908915195623,16.4778406992115,18.125152652895,16.3001894100888,16.0579376521941,17.495298082369,16.816993160264,17.2207460900884,16.5747414023693,17.6567992542987,16.4455404648255,16.816993160264,15.2342816753523,18.0444020669301,16.4616905820185,16.6554919883342,15.8479861286854,17.8667507778074,17.3660971448252],"mode":"lines","text":{},"name":"lm-alcohol","color":["indianred1"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","line":{"color":["indianred1"],"width":2},"inherit":true},"98d32d4bbc6f":{"x":{},"y":{},"mode":"markers","text":{},"name":"temperature","color":["brown"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"},"98d32d4bbc6f.1":{"x":{},"y":[15.2366722692261,19.9766692537659,15.0429285295483,15.5363544911859,15.7961843507795,18.3898276376351,17.8668595647382,16.5022805241392,13.5371893547097,15.0245740994792,13.3896750915843,18.2747590957092,17.3088428081695,17.3401068444318,18.0203666949512,16.6285473494083,16.4148922765143,14.4231241900277,18.7821979056868,16.3471710230471,18.1501587361543,18.257645774721,18.7589416007602,14.9846959650805,16.679868999563,18.7582584847538,17.6637663393226,17.4524063368719,18.6349079744845,16.8142621342902,16.869898137917,18.3502085774388,15.9216552731504,19.2417578737984,17.5278653549788,15.718080215932,17.4148967197356,17.8256932001546,17.0343737376814,15.3765463085688,18.3965451093203,16.1107508140685,14.6521077014995,17.8872630872648,18.6150065281667,16.8082051723674,17.5313568367889,17.0429204587307,18.5313190672564,18.8681010085127],"mode":"lines","text":{},"name":"lm-temperature","color":["brown"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","line":{"color":["brown"],"width":2},"inherit":true},"98d3474032a4":{"x":{},"y":{},"mode":"markers","text":{},"name":"precipitation","color":["orange"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"},"98d3474032a4.1":{"x":{},"y":[15.2431784527589,15.3397909276739,19.3975148741002,15.9194657771633,18.528002599866,19.2042899242704,16.1126907269932,16.305915676823,15.4364034025888,15.8228533022484,10.0261048073536,18.8178400246107,16.9822030012274,16.7889780513976,17.5618778507169,18.0449402252914,16.1126907269932,15.146565977844,16.6923655764826,16.4991406266528,16.305915676823,17.5618778507169,18.1415527002063,15.2431784527589,16.7889780513976,19.2042899242704,18.528002599866,18.528002599866,16.5957531015677,16.305915676823,19.3975148741002,16.8855905263125,15.8228533022484,19.0110649744406,16.9822030012274,17.4652653758019,17.9483277503765,16.6923655764826,16.4025281517379,16.0160782520782,18.9144524995256,15.6296283524186,18.0449402252914,19.4941273490151,16.8855905263125,16.4991406266528,16.9822030012274,16.4025281517379,17.6584903256318,19.3975148741002],"mode":"lines","text":{},"name":"lm-precipitation","color":["orange"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","line":{"color":["orange"],"width":2},"inherit":true},"98d347bcd187":{"x":{},"y":{},"mode":"markers","text":{},"name":"marijuana","color":["snow4"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"},"98d347bcd187.1":{"x":{},"y":[16.0921812208209,18.7523330242034,16.8216447231547,16.5390035940453,17.5843601230308,19.2137031026026,17.2850930451502,16.9837477236733,16.7322802485098,16.331179234406,16.6449940174613,16.5223776452741,16.7676103896485,16.9047744670104,16.2750666573034,16.3665093755447,16.574333735184,16.4766562861535,18.5507433953533,17.13545950621,18.0976862913397,17.4035529301446,16.7468279536846,16.2688319265143,16.7821580948232,18.0104000602913,16.2646754393215,17.4284918533013,17.8108886750376,16.4205437090509,17.5635776870668,16.9463393389382,16.4247001962437,16.1732327210802,16.775923364034,16.4143089782617,19.5732392447785,16.6824024021964,18.2971976765934,16.1981716442369,16.4454826322076,16.6990283509675,16.1004941952064,16.0817900028389,18.9414531914751,16.3602746447555,18.7066116650828,16.6055073891299,16.5244558888705,16.4163872218581],"mode":"lines","text":{},"name":"lm-marijuana","color":["snow4"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","line":{"color":["snow4"],"width":2},"inherit":true},"98d33d601adc":{"x":{},"y":{},"mode":"markers","text":{},"name":"education","color":["plum"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"},"98d33d601adc.1":{"x":{},"y":[19.1337990698801,17.4578327349666,17.6614518608229,20.0711329525659,16.1106018389272,13.5371096470645,13.9121998707415,16.7143617507574,17.6593701252351,17.103731705314,16.3128464074754,18.2921689964989,15.7833699323036,18.8354108946782,17.9484745429906,16.1957429179171,19.6340102933468,19.5571386170697,16.9723022434687,13.7005033319482,12.5392066435215,17.7983538139942,15.289370476118,20.3317012584641,17.7587391590813,16.8040684820301,16.8556990433038,19.4491072194732,14.8110122401935,14.039673867986,18.2517355650667,15.0917689117791,17.1304059098834,17.4936966323466,18.11466644177,19.0141838596731,16.2251187680622,17.0464251622309,15.9647799919791,18.2023771039709,17.88609262259,18.5598439279134,17.5638679203241,16.1251959322567,14.5249982749915,14.2404965272567,15.4018975859934,20.8707410271533,17.4416487345465,18.2982540461459],"mode":"lines","text":{},"name":"lm-education","color":["plum"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","line":{"color":["plum"],"width":2},"inherit":true},"98d3708380fe":{"x":{},"y":{},"mode":"markers","text":{},"name":"gdp","color":["royalblue1"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"},"98d3708380fe.1":{"x":{},"y":[18.7517713764334,14.1109571090514,18.5173913761552,18.8510594381687,15.6720362251532,16.3799901926173,14.7063846065488,14.6623067245967,18.4152450217336,17.6901412981516,16.7262949170334,18.960727615449,16.2581366623058,17.5571554700092,16.7614970480123,17.2422919651426,18.4889588857492,17.6329754444252,18.5119756636969,16.0381985619164,14.5920528990961,17.8830008362496,16.2659593580788,19.5375009922568,17.8360646616111,18.326036202629,16.3414784595805,17.7298565228457,16.7058355588576,15.8008098324947,18.0415608621117,14.6543335923664,17.6626114264886,14.1711316919213,17.2519198984017,17.3966397702038,16.8057253664216,16.7115521442303,17.2079924529067,18.7607975638639,17.119535816088,17.8580283843586,16.10935500616,17.6463642891138,17.7530237372506,16.5162856228175,15.9049118608596,18.8123972686748,17.246955495315,15.1334737084678],"mode":"lines","text":{},"name":"lm-gdp","color":["royalblue1"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","line":{"color":["royalblue1"],"width":2},"inherit":true},"98d34989dd67":{"x":{},"y":{},"mode":"markers","text":{},"name":"gender","color":["purple1"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"},"98d34989dd67.1":{"x":{},"y":[12.8733977928113,28.3615607246268,18.102027666523,15.7623356727487,18.0109343714258,20.5693563082622,14.5202463081677,12.809005467205,14.7479200859804,13.8970967951512,19.8812570837159,19.6946538813987,15.8429347984907,16.454941669374,18.199879758303,18.6001045995354,16.2903818192442,14.7328518367188,15.2121476618955,13.1594870140665,13.4309612926842,16.1260546315135,18.4108030965428,13.0466108754277,15.6663493283926,20.6437881631565,18.8350732188681,19.8627703366297,17.3301695072798,14.5156604878811,17.3384461940633,13.4471127108813,13.968295107491,24.3139672707161,15.2475054288394,17.4147366244491,17.4566522803873,15.1287732792278,13.6377727573338,13.3046371397464,21.1292291943963,14.3495103510607,17.9538412859173,20.6203716079167,16.9421146954045,16.0092836816165,19.2645903332693,17.1828079450007,18.1971855726729,23.2210911696603],"mode":"lines","text":{},"name":"lm-gender","color":["purple1"],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter","line":{"color":["purple1"],"width":2},"inherit":true}},"source":"A","config":{"showSendToCloud":false},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"subplot":true,"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
<div id="multiple-linear-regression" class="section level2">
<h2>Multiple linear regression</h2>
<div id="model-building" class="section level3">
<h3>Model building</h3>
<p>Next, we used automatic procedures (stepwise elimination) to cut down covariates.</p>
<pre class="r"><code>fit1 = lm(suicide ~.-state,data = regression_data)
step(fit1) </code></pre>
<pre><code>## Start:  AIC=80.99
## suicide ~ (state + gun + alcohol + temperature + precipitation + 
##     marijuana + education + gdp + gender) - state
## 
##                 Df Sum of Sq    RSS     AIC
## - alcohol        1     0.040 176.27  78.999
## - precipitation  1     0.206 176.43  79.046
## &lt;none&gt;                       176.23  80.987
## - temperature    1    13.963 190.19  82.800
## - education      1    30.539 206.77  86.978
## - marijuana      1    33.321 209.55  87.647
## - gun            1    50.987 227.21  91.693
## - gdp            1    60.008 236.23  93.640
## - gender         1   230.078 406.31 120.754
## 
## Step:  AIC=79
## suicide ~ gun + temperature + precipitation + marijuana + education + 
##     gdp + gender
## 
##                 Df Sum of Sq    RSS     AIC
## - precipitation  1     0.239 176.51  77.067
## &lt;none&gt;                       176.27  78.999
## - temperature    1    14.916 191.18  81.060
## - education      1    30.554 206.82  84.992
## - marijuana      1    36.734 213.00  86.464
## - gun            1    54.555 230.82  90.481
## - gdp            1    60.536 236.80  91.760
## - gender         1   230.865 407.13 118.856
## 
## Step:  AIC=77.07
## suicide ~ gun + temperature + marijuana + education + gdp + gender
## 
##               Df Sum of Sq    RSS     AIC
## &lt;none&gt;                     176.51  77.067
## - temperature  1    16.667 193.17  79.578
## - education    1    31.270 207.78  83.222
## - marijuana    1    38.487 214.99  84.929
## - gun          1    54.864 231.37  88.600
## - gdp          1    60.935 237.44  89.895
## - gender       1   236.423 412.93 117.563</code></pre>
<pre><code>## 
## Call:
## lm(formula = suicide ~ gun + temperature + marijuana + education + 
##     gdp + gender, data = regression_data)
## 
## Coefficients:
## (Intercept)          gun  temperature    marijuana    education  
##  -1.440e+02    1.220e-01   -9.552e-02    2.485e-01   -2.343e-01  
##         gdp       gender  
##  -1.815e-04    3.559e+00</code></pre>
<pre class="r"><code>fit2 = lm(suicide ~ gun + temperature + marijuana + education + gender +gdp, data = regression_data)
fit2 %&gt;% 
  broom::tidy() %&gt;% 
  knitr::kable(digits = 4)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-143.9870</td>
<td align="right">24.3248</td>
<td align="right">-5.9194</td>
<td align="right">0.0000</td>
</tr>
<tr class="even">
<td align="left">gun</td>
<td align="right">0.1220</td>
<td align="right">0.0334</td>
<td align="right">3.6559</td>
<td align="right">0.0007</td>
</tr>
<tr class="odd">
<td align="left">temperature</td>
<td align="right">-0.0955</td>
<td align="right">0.0474</td>
<td align="right">-2.0150</td>
<td align="right">0.0502</td>
</tr>
<tr class="even">
<td align="left">marijuana</td>
<td align="right">0.2485</td>
<td align="right">0.0811</td>
<td align="right">3.0621</td>
<td align="right">0.0038</td>
</tr>
<tr class="odd">
<td align="left">education</td>
<td align="right">-0.2343</td>
<td align="right">0.0849</td>
<td align="right">-2.7601</td>
<td align="right">0.0085</td>
</tr>
<tr class="even">
<td align="left">gender</td>
<td align="right">3.5589</td>
<td align="right">0.4689</td>
<td align="right">7.5893</td>
<td align="right">0.0000</td>
</tr>
<tr class="odd">
<td align="left">gdp</td>
<td align="right">-0.0002</td>
<td align="right">0.0000</td>
<td align="right">-3.8529</td>
<td align="right">0.0004</td>
</tr>
</tbody>
</table>
<pre class="r"><code>fit2 %&gt;% 
  broom::glance() %&gt;%   
  knitr::kable(digits = 4)</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.8354</td>
<td align="right">0.8124</td>
<td align="right">2.026</td>
<td align="right">36.3648</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">-102.4802</td>
<td align="right">220.9604</td>
<td align="right">236.2566</td>
<td align="right">176.5058</td>
<td align="right">43</td>
</tr>
</tbody>
</table>
</div>
<div id="model-diagnosis" class="section level3">
<h3>Model diagnosis</h3>
<pre class="r"><code>par(mfrow = c(2,2))
plot(fit2)</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Basically, the residual assumptions are satisfied. However, 26 and 50 may be influential. Then, we tried to fit model without 26 and 50.</p>
<pre class="r"><code>fit3 = lm(suicide ~ gun + temperature + marijuana + education + gender +gdp, data = regression_data[-c(26,50),])
par(mfrow = c(2,2))
plot(fit3)</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>fit3 %&gt;% 
  broom::tidy() %&gt;% 
  knitr::kable(digits = 4)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-124.8903</td>
<td align="right">19.0036</td>
<td align="right">-6.5719</td>
<td align="right">0.0000</td>
</tr>
<tr class="even">
<td align="left">gun</td>
<td align="right">0.1277</td>
<td align="right">0.0257</td>
<td align="right">4.9753</td>
<td align="right">0.0000</td>
</tr>
<tr class="odd">
<td align="left">temperature</td>
<td align="right">-0.0659</td>
<td align="right">0.0368</td>
<td align="right">-1.7906</td>
<td align="right">0.0807</td>
</tr>
<tr class="even">
<td align="left">marijuana</td>
<td align="right">0.2668</td>
<td align="right">0.0628</td>
<td align="right">4.2472</td>
<td align="right">0.0001</td>
</tr>
<tr class="odd">
<td align="left">education</td>
<td align="right">-0.2224</td>
<td align="right">0.0667</td>
<td align="right">-3.3327</td>
<td align="right">0.0018</td>
</tr>
<tr class="even">
<td align="left">gender</td>
<td align="right">3.1119</td>
<td align="right">0.3692</td>
<td align="right">8.4287</td>
<td align="right">0.0000</td>
</tr>
<tr class="odd">
<td align="left">gdp</td>
<td align="right">-0.0002</td>
<td align="right">0.0000</td>
<td align="right">-4.5129</td>
<td align="right">0.0001</td>
</tr>
</tbody>
</table>
<p>The coefficients of model changed slightly, except for temperature(over 10%). We decided to retain 26 and 50.</p>
</div>
<div id="visualize-model-coefficients" class="section level3">
<h3>Visualize model coefficients</h3>
<pre class="r"><code>GGally::ggcoef(fit2,aes(x = estimate, y = term, color =  term),size = 0.8,
               exclude_intercept = T,sort = &quot;ascending&quot;) +
  labs(title = &quot;95% CI for Model Coefficients&quot;)</code></pre>
<p><img src="report_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p><strong>Results:</strong></p>
<ul>
<li><p>The “alcohol” and “precipitation” were removed from the model.</p></li>
<li><p>The fitted equation is “suicide = -143.99 + 0.12gun - 0.10temperature + 0.25marijuana - 0.23education + 3.56gender - 0.0002gdp”.</p></li>
<li><p>Adjusted R-square is 0.8124, which means these variables can explain a large proportion of variance in the suicide rate.</p></li>
<li><p>According to the results, the suicide rate is higher in states where there is a higher gun ownership rate, higher marijuana usage, higher ratio of males to females, lower temperature and lower educational attainment.</p></li>
<li><p>Holding other variables constant, for one unit increase in gun ownership(per 1,000), marijuana use in adults(%), or for one unit decrease in proportion of male (%), GDP per capita (dollars), the suicide rate(per 100k population) will increase by 0.13, 0.27, 3.11 respectively, or decrease by 0.22, 0.0002 on average.</p></li>
</ul>
</div>
</div>
</div>
<div id="discussion" class="section level1">
<h1>Discussion</h1>
<p>Multiple risk factors are responsible for suicide. From our linear regression model, the suicide rate in 50 states in the U.S. is significantly associated with gender, gun ownership rates, average temperature, marijuana use, the degree of education and GDP. However, future suicide rate could not be limited by these variables. While suicide is a global phenomenon, further study needs to be conducted to determine the generalization of our model and hypothesis.</p>
<p>In this project, we do gain several insights about risk factors for suicide rate in the U.S.. Firstly, gender matters. Men are at higher risk of suicide compared to women, which may be explained by the different socioeconomic status owned and the degree of pressure are faced. Other important factors are the marijuana use and the gun ownership rates. This highlights that legislation needs to be improved for restrictions in drugs and guns to prevent suicide. What’s more, the average temperature, degree of education and GDP are all negatively correlated with the suicide rate.</p>
<p>With the visualization of geographic variation of these risk factors in the U.S., we get insights into target states with higher prevalence of risk factors. We hope that our project could help to solve the puzzle for suicide cause and increase the awareness of the public.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
