---
title: "Final report"
output: 
  html_document:
    toc: true
    toc_float: true
---
# Motivation

## Some facts about suicide

* About 800,000 people died by suicide in global every year, which accounts for 1.4% of all deaths worldwide.

* The annual U.S. suicide rate increased 10% between 2014 and 2017 according to the CDC’s NCHS

* In 2015, suicide has become the second leading cause of death among 15-34 age group and the third leading cause of death between the ages of 10-14 in the USA.

* It is reported that in 2016 suicide was the 10th leading cause of death in the U.S., imposing a cost of $69 billion to the US annually.


On the one hand, almost all the risk factors for the suicide are preventable. Usually, people are not aware of the risk factors of suicide and situate themselves in the dangerous environment. We believe that a better understanding of potential risk factors is essential for the prevention of suicide.

On the other hand, the suicide rate in the USA increases overtime while it decrease in global. Therefore, we want to focus on the U.S. to explore the risk factors and promote effective preventive measures.

## Goal of our project

* Understanding risk factors for suicide

* Visualizing correlations of these risk factors with suicide

* Visualizing the distribution of risk factors and suicide in the U.S.


# Related Work



# Initial Question

We aim to examine the risk factor for suicide and suicide rate in the USA. We want to visualize the association and data in innovative and interactive way. As stated above, our questions are as follows:

* What are potential risk factors for suicide? How could we visualize the association between these factors and suicide rate?

* How could we use shiny to visualize the distribution of risk factors and suicide rate in the USA?

* Could the model be generalized to other regions? How can we predict suicide rate using the constructed model?





# Tidy the Data

## Data Import

## Data Cleaning

## Final Dataset

After we collecting data from different sources, we constructed a [merged dataset](./data/US_2017.csv) collecting multiple protential risk factors for suicide rate in different states in US, here is the discriptions:

**Suicide rate (2017)**: The number of suicide deaths cases per 100000 people in 2017.

**Female proportion (2017)**: The proportion of Female in 2017.

**Male proportion (2017)**: The proportion of Male in 2017.

**Female Suicide rate (2017)**: The number of female suicide deaths cases per 100000 females in 2017.

**Male Suicide rate (2017)**: The number of male suicide deaths cases per 100000 males in 2017.

**Age 5-14 (2017)**: The proportion of people between age 5-14 in 2017.

**Age 15-24 (2017)**: The proportion of people between age 15-24 in 2017.

**Age 25-34 (2017)**: The proportion of people between age 25-34 in 2017.

**Age 35-44 (2017)**: The proportion of people between age 35-44 in 2017.

**Age 45-54 (2017)**: The proportion of people between age 45-54 in 2017.

**Age 55-64 (2017)**: The proportion of people between age 55-64 in 2017.

**Age 65-74 (2017)**: The proportion of people between age 65-74 in 2017.

**Age 75-84 (2017)**: The proportion of people between age 75-84 in 2017.

**Age >85 (2017)**: The proportion of people between age over 85 in 2017.

**Alcohol consumption (2017)**: Alcohol consumption per capita in gallons in 2017.

**Marijuana usage (2017)**: Marijuana users percentage in 2017.

**Advanced degree (2017)**: The proportion of people who have advanced degree in 2017.

**Bachelors degree(2017)**: The proportion of people who have Bachelors degree in 2017.

**College degree (2017)**: The proportion of people who have College degree in 2017.

**Below college degree (2017)**: The proportion of people who have below college degree in 2017.

**GDP (2017)**: Gross Domestic Product in 2017.

**Guns number per capita (2017)**: Averaged guns number per capita in 2017.

**Guns number registered (2017)**: Averaged guns number registered in 2017

**Precipitation**: Averaged Precipitation in inches.

**Temperature**: Averaged Temperature in F.

Another dataset we used is [worldwild suicide distribution dataset](./data/suicide_age_gender.xlsx) from 1999 to 2017. In this dataset, we have information about number of suicide cases in different year, country, gender and age groups and the population in each groups. Using this dataset, we can analyze how suicide cases change worldwild in time and how suicide cases distributed in different gender and age groups.


# Subanalyses

## World-level insight

## US-level insight

To show how the suicide cases distributed in different states, we made a Crude Suicide Rate map allowing users to toggle between different years (1999-2017) and choose gender, demonstrating the changes in suicide rate over time and visualize regional differences across the U.S. The map demonstrates that there are significant changes over time and gender.

The line plot we made is to show the change of total suicide rate by year in US. We can see a stable increase by year and the truth that there are much more cases of suicide in male than in female.

To show the distribution of the risk factors, we construct a US map allowing users to choose the types of variables, visualizing regional differences across the U.S and a bar plot showing the intuitive number in different states. Users are also allowed to choose TOP n states they want to explore in both plots.

# Regression Analysis



# Discussion 



