---
title: "scater plot"
author: "Yue Lai"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(corrplot)
```

## tidy data

```{r}
us_data = read_csv("../data/us_2017.csv") %>% 
  filter(state != "District of Columbia") %>%  
  mutate(
    suicide = suicide_rate_per100000,
    gun = number_of_guns_per_capita,
    alcohol = alcohol_consumption_per_capita_gallons,
    temperature = mean_temperature_F, 
    precipitation = precipitation_inches,
    marijuana = marijuana_percentage * 100,
    education = (advanced_degree + bachelors_degree) * 100,
    gender = male_ratio * 100
    ) %>% 
  select(state, suicide, gun, alcohol, temperature, precipitation, marijuana, education, gdp, gender) %>% 
  # replace missing value with mean value
  mutate(
    gun = replace_na(gun, mean(gun, na.rm = TRUE)),
    temperature = replace_na(temperature, mean(temperature, na.rm = TRUE)))
```

## make scatter plot

```{r}
# gun
us_data %>% 
  ggplot(aes(x = gun, y = suicide)) +
  geom_point() +
  labs(x = "Number of guns per 1000 population", 
       y = "Suicide rate per 100000 population")

# alcohol
us_data %>% 
  ggplot(aes(x = alcohol, y = suicide)) +
  geom_point() +
  labs(x = "Alcohol consumption per capita (gallons of ethanol)"， 
       y = "Suicide rate per 100000 population")

# temperature
us_data %>% 
  ggplot(aes(x = temperature, y = suicide)) +
  geom_point() +
  labs(x = "Average temperature (F)", 
       y = "Suicide rate per 100000 population")

# precipitation
us_data %>% 
  ggplot(aes(x = precipitation, y = suicide)) +
  geom_point() +
  labs(x = "Average precipitation (inches)",
       y = "Suicide rate per 100000 population")

# marijuana
us_data %>% 
  ggplot(aes(x = marijuana, y = suicide)) +
  geom_point() +
  labs(x = "Marijuana use in adults (%)", 
       y = "Suicide rate per 100000 population")

# education
us_data %>% 
  ggplot(aes(x = education, y = suicide)) +
  geom_point() +
  labs(x = "Educational attainment - bachelor's degree or higher (%) ",
       y = "Suicide rate per 100000 population")

# gdp
us_data %>% 
  ggplot(aes(x = gdp, y = suicide)) +
  geom_point() +
  labs(x = "GDP per capita (dollars)",
       y = "Suicide rate per 100000 population")

# gender
us_data %>% 
  ggplot(aes(x = gender, y = suicide)) +
  geom_point() +
  labs(x = "Male (%)",
       y = "Suicide rate per 100000 population")

# no data about average age 
```

# make a correlation plot

```{r}
us_data %>% 
  select(-state) %>% 
  cor() %>% 
  corrplot(
    tl.col = "black", 
    tl.cex = .8, 
    addCoef.col = "black",
    order = "AOE",
    method = "color",
    number.cex = .7)
```

```{r}
fit1 = lm(suicide ~.-state,data = us_data)
summary(fit1)
step(fit1)

fit2 = lm(suicide ~ gun + temperature + marijuana + education +  gender +gdp, data = us_data)
summary(fit2)
anova(fit2)
plot(fit2)

```
As the regression shows, "gun", "marijuana","education","gender","gdp" are significant predictors for suicide rate. 
